### ISSUE TITLE
Desktop Client *Occasionally* Not Updating Scores

### ISSUE THREAD

**Issue by asangster** [RaiderIO/raiderio-addon#101]
See below: Data refresh is up to date, but what is shown on the desktop client doesn't match what is on the website. 

![image](https://user-images.githubusercontent.com/12052782/55280535-dc338900-531e-11e9-8e47-e06e48d3129d.png)

Thanks!

**Comment by jahraphael** [comment]
There may not be enough info to really do anything with here.

One question: If you hit "Refresh Addon" in these cases, does the data sync up with what is on the site? If that's the case, then it's just expected behavior. But I expect you probably tried refreshing?

**Comment by asangster** [comment]
@jahraphael I did indeed - that screenshot was taken 10 secs after hitting refresh. The next day or so after, the updated score was shown on the client

**Comment by jahraphael** [comment]
Client 1.3.0 did add some cache invalidation on refresh.  I'm going to go ahead and close this issue.  If it's still happening on the latest client then feel free to re-open and provide some additional information.
