### ISSUE TITLE
Addon not updating

### ISSUE THREAD

**Issue by Necrosaro420** [RaiderIO/raiderio-addon#102]
I update everyday via curse/twitch, but my scores are not updating in game.  And when it does its taking like a week + to do so.

**Comment by kaseyd24** [comment]
I am doing the same.. its not updating via twitch.

**Comment by WFrancois** [comment]
Hi, this is weird, what's the version you have when you type `/raiderio` in game ? The version is shown at the top of the window.

Keep in mind that you need to update the addon every day to keep data up to date.

**Comment by kaseyd24** [comment]
Apparently there might be an issue with twitch/curse?  Its just these two addons.. Raiderio, and DBM... it says to update in the twitch window, but when you do, it looks like its installing, but a refresh shows it was not installed or downloaded.

**Comment by jahraphael** [comment]
Have you tried restarting the Twitch client? We've seen in the past sometimes the client keeps caching an old version of the addon and not really updating it, even when there is a new version available.

**Comment by neologic1** [comment]
> Have you tried restarting the Twitch client? We've seen in the past sometimes the client keeps caching an old version of the addon and not really updating it, even when there is a new version available.

this doesnt work, i can update the addon, refresh, and it still doesnt download, ive tried restarting computer, twitch, WoW, everything. dont know what the problem is.

**Comment by kaseyd24** [comment]
> Have you tried restarting the Twitch client? We've seen in the past sometimes the client keeps caching an old version of the addon and not really updating it, even when there is a new version available.

Yes, this has been an ongoing issue for about a week and a half???

**Comment by jahraphael** [comment]
This sounds like it's a Twitch issue, and you should reach out to Twitch Client support to try to resolve it. But here's something to check to confirm:

- Make sure you aren't running the Raider.IO client, just to rule out any incompatibility
- Go here and look at what the latest version of the Raider.IO addon is that is uploaded to Twitch: https://wow.curseforge.com/projects/raiderio/files
- Go into your Twitch client, refresh your addons, then update the Raider.IO addon
- Load into WoW and type `/raiderio`. Look at the top of that window.

If the version number in the `/raiderio` window doesn't match the version that was shown on the Twitch website, then the Twitch Client is installing the wrong version, and you should reach out to them.

If the version numbers match and your scores are still not showing, then join our Discord and bring the issue up in #bug-reports so we can have people get to the bottom of it: https://discord.gg/raider
