### ISSUE TITLE
Update Looping in Twitch Client

### ISSUE THREAD

**Issue by IOnine** [RaiderIO/raiderio-addon#103]
Addon 'updates' then shows new update available in twitch client. I'm not sure if this is an issue with the client or the addon. The included zip includes a screencap of the process in MP4 format
[RaiderIOTwitch.zip](https://github.com/RaiderIO/raiderio-addon/files/3123902/RaiderIOTwitch.zip)

**Comment by jahraphael** [comment]
If using both the Raider.IO Client and the Twitch client, you will want to set the Raider.IO to be ignored in the Twitch Client. Otherwise you will get the issue you are seeing, because the Raider.IO Client is able to get you newer data than what the Twitch client has access to most of the time.
