### ISSUE TITLE
Raider.io resetting when changing race

### ISSUE THREAD

**Issue by kroyer1996** [RaiderIO/raiderio-addon#108]
When i last time changed class my entire Raider.io resetted to zero, and that is a huge problem because i have plans to change to zandalari troll now cause i didnt had them last time. please respond fast as possible before i change and ofc no worries doing more right now if it is in vain:)

**Comment by jahraphael** [comment]
Take a look here: https://raiderio.reamaze.com/kb/server-slash-faction-transfer-or-rename/i-am-planning-to-transfer-servers-how-do-i-copy-my-mythic-plus-score

If you ever have any problems after xfer, join [our discord](https://discord.gg/raider) and post in #support - someone will be able to help out.
