### ISSUE TITLE
WoW 8.2 Error opening Guild & Communities

### ISSUE THREAD

**Issue by geeksbsmrt** [RaiderIO/raiderio-addon#109]
Message: Interface\AddOns\RaiderIO\core.lua:2433: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Jun 25 21:42:18 2019
Count: 1
Stack: Interface\AddOns\RaiderIO\core.lua:2433: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\RaiderIO\core.lua:2433: in function `func'
Interface\AddOns\RaiderIO\core.lua:1934: in function <Interface\AddOns\RaiderIO\core.lua:1929>
Interface\AddOns\RaiderIO\core.lua:1964: in function `?'
Interface\AddOns\RaiderIO\core.lua:3017: in function <Interface\AddOns\RaiderIO\core.lua:3017>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:450: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:696: in function `Communities_LoadUI'
Interface\FrameXML\UIParent.lua:930: in function `ToggleCommunitiesFrame'
Interface\FrameXML\UIParent.lua:817: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by WFrancois** [comment]
Hi !

Thanks for reporting this issue, I've made a change to disable this feature on Guild & Communities until a fix is done :)

**Comment by Vladinator89** [comment]
I took a look at the code and Blizzard changed to the buttons being created when needed, instead of created when the addon loads. I'll keep an eye on this but think this should solve this and restore original functionality.
