### ISSUE TITLE
Wont load/update in Twitch app

### ISSUE THREAD

**Issue by kroyer1996** [RaiderIO/raiderio-addon#120]
The addon suddenly stopped updating and i need it in order to see my new io scores

**Comment by WFrancois** [comment]
Hi !

How do you update your addon ?

If you're updating on twitch, as shown on https://www.curseforge.com/wow/addons/raiderio/files there is a file uploaded every day (although some update was missing 2 days ago).

If you're updating with the client (https://raider.io/addon), do you have an error displayed on it ?

Thanks :)

**Comment by kroyer1996** [comment]
Scanned my character many times in Raider.io and reinstalled raider.io also many times. And when i do it in the website it still tells me the same io even tho i have completed a recent run, and that is showing in there but aint changing my io still :o 
- using twitch app

**Comment by WFrancois** [comment]
Oh, so it's the raiderio website that isn't up to date ?

If you can join RaiderIO's discord it might be easier and faster to help out :) 
https://discord.gg/raider
