### ISSUE TITLE
WOW Addon not refreshing with updated stats and completed M+ dungeons

### ISSUE THREAD

**Issue by j0etharris** [RaiderIO/raiderio-addon#124]
The WOW addon for RaiderIO is not refreshing with updated stats and completed M+ dungeons. I have uninstalled the addon and reinstalled the addon without success. I am using Windows 10 Pro and my account is an administrator account. I have the desktop version also and it is up-to-date, but the WOW addon is not updating.

**Comment by WFrancois** [comment]
Hi, is your character on the RaiderIO website up to date ?
