### ISSUE TITLE
daily database doesn´t update automatically in Twitch client

### ISSUE THREAD

**Issue by Paragalla** [RaiderIO/raiderio-addon#129]
although i set both marks in install settungs to automatically and version type even to alpha...

Is it a twitch problem
or a setting problem
or a programmers problem ?

who can help ?

Para :-)

**Comment by jahraphael** [comment]
This would be a Twitch problem. The addon is pushed to Curse each day, and you can see the latest versions here: https://www.curseforge.com/wow/addons/raiderio/files

We created our own desktop client to simplify this process and work around any potential issues with the Twitch client. This will also give you more frequent data updates. You can download it here: https://raider.io/addon
