### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Markoolio** [RaiderIO/raiderio-addon#132]
32x [string "--[==[ Error in 'Utility':'initialization' ..."]:44: attempt to index global 'MDT' (a nil value)
[string "--[==[ Error in 'Utility':'initialization' ]==] return function() aura_env.keyslot = aura_env.config["KeySlot"]
aura_env.gossipS = aura_env.config["GossipS"]
aura_env.blacklist = {
    -- [123] = true
}

aura_env.popup = function()
    for index = 1, STATICPOPUP_NUMDIALOGS do
        local frame = _G["StaticPopup"..index]
        if frame and frame:IsShown() then
            return true
        end
    end
    return false
end

local function decRound(num, idp)
    local mult = 10^(idp or 0)
    return math.floor(num * mult + 0.5) / mult
end

local _, affixes = C_ChallengeMode.GetActiveKeystoneInfo()
local teeming = false
for _, affixID in ipairs(affixes) do
    if affixID == 5 then
        teeming = true
    end
end

local tooltip = aura_env.config["Tooltip"]
local function addtotooltip(self, unit)
    local GUID = UnitGUID("mouseover")
    if GUID then
        local npcID = select(6, strsplit("-", GUID))
        local count = 0
        local max = 0
        if teeming then
            max, count = select(3, MDT:GetEnemyForces(tonumber(npcID)))
        else
            count, max = MDT:GetEnemyForces(tonumber(npcID))
        end
        if count and max and count ~= 0 and max ~= 0 then
            local percent = decRound((count/max)*100, 2).."%"
            
            local string = (tooltip  == 4 and count.." ("..percent..")") or (tooltip  == 3 and percent) or (tooltip  == 2 and count)
            if string then
                GameTooltip:AppendText(" - "..string)
            end
        end
    end
end

if not aura_env.region.addtotooltip then
    aura_env.region.addtotooltip = true
    hooksecurefunc(GameTooltip, "Show", addtotooltip)
end

 end"]:44: in function <[string "--[==[ Error in 'Utility':'initialization' ..."]:35>
[string "=[C]"]: in function `Show'
[string "@RaiderIO\core.lua"]:1967: in function <RaiderIO\core.lua:1928>
[string "@RaiderIO\core.lua"]:2375: in function <RaiderIO\core.lua:2366>
[string "=[C]"]: ?

Locals:
self = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 1
 Show = <function> defined =[C]:-1
 comparing = false
 shoppingTooltips = <table> {
 }
 TopOverlay = <unnamed> {
 }
 ItemTooltip = <unnamed> {
 }
 default = 1
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 updateTooltip = 0.021000
 hasMoney = 1
}
unit = nil
GUID = "Player-1403-0826A46A"
npcID = nil
count = 0
max = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "0826A46A"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'MDT' (a nil value)"
teeming = false
decRound = <function> defined --[==[ Error in 'Utility':'initialization' ]==] return function() aura_env.keyslot = aura_env.config["KeySlot"]
aura_env.gossipS = aura_env.config["GossipS"]
aura_env.blacklist = {
    -- [123] = true
}

aura_env.popup = function()
    for index = 1, STATICPOPUP_NUMDIALOGS do
        local frame = _G["StaticPopup"..index]
        if frame and frame:IsShown() then
            return true
        end
    end
    return false
end

local function decRound(num, idp)
    local mult = 10^(idp or 0)
    return math.floor(num * mult + 0.5) / mult
end

local _, affixes = C_ChallengeMode.GetActiveKeystoneInfo()
local teeming = false
for _, affixID in ipairs(affixes) do
    if affixID == 5 then
        teeming = true
    end
end

local tooltip = aura_env.config["Tooltip"]
local function addtotooltip(self, unit)
    local GUID = UnitGUID("mouseover")
    if GUID then
        local npcID = select(6, strsplit("-", GUID))
        local count = 0
        local max = 0
        if teeming thentooltip = 4

**Comment by Vladinator89** [comment]
Thanks for the report. This seems to have been an issue with weakauras and not directly RIO and since it's been a while since this error, and we did upgrade the addon last week I hope this has since been fixed by the weakauras author for that weakaura.
