### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by KirbyV2** [RaiderIO/raiderio-addon#134]
Message: Interface\FrameXML\UnitFrame.lua:458: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
Time: Sun Aug  2 17:42:12 2020
Count: 1
Stack: Interface\FrameXML\UnitFrame.lua:458: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[string "=[C]"]: in function `SetUnit'
[string "@Interface\FrameXML\UnitFrame.lua"]:458: in function `UnitFrame_UpdateTooltip'
[string "@Interface\FrameXML\UnitFrame.lua"]:448: in function `oe'
[string "@Interface\AddOns\RaiderIO\core.lua"]:2000: in function <Interface\AddOns\RaiderIO\core.lua:1974>
[string "@Interface\AddOns\RaiderIO\core.lua"]:2054: in function <Interface\AddOns\RaiderIO\core.lua:2051>
[string "@Interface\AddOns\RaiderIO\core.lua"]:2299: in function `?'
[string "@Interface\AddOns\RaiderIO\core.lua"]:3201: in function <Interface\AddOns\RaiderIO\core.lua:3201>

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 icon = <unnamed> {
 }
 MAScaled = 0.700000
 TopOverlay = <unnamed> {
 }
 default = 1
 MAMover = TooltipMover {
 }
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.058000
 SetInventoryItem = <function> defined =[C]:-1
 __tamedCounts = false
 comparing = false
 SetLootRollItem = <function> defined =[C]:-1
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetInboxItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined @Interface\AddOns\Altoholic\Tooltip.lua:700
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil

**Comment by Vladinator89** [comment]
It looks like an unit was attempted to be set (when the tooltip was being updated) but there was no unit and it all crashed. Makes sense. Now since we did update the whole code base recently, we just have to assume that this was fixed in that upgrade, but do let me know if this happens again with the latest version. Thanks for the report.
