### ISSUE TITLE
Score won't update

### ISSUE THREAD

**Issue by LAAAALZ** [RaiderIO/raiderio-addon#135]
Hi, 

For 4 days, score in game won't update for some reason. Still seeing 3967 but i'm 4064 for 4 days. 

Raider IO is updated in twitch everything but still not showing the right thing in game.

**In game screenshot** : 

![riorio](https://user-images.githubusercontent.com/69647636/90172678-a708c900-dda3-11ea-9cec-f845934ce576.PNG)

**RaiderIo website** : https://raider.io/characters/eu/uldaman/Laalz 

Any ideas ? 

Thank's by advance :)
LALZ

**Comment by WFrancois** [comment]
Hey there !

We're pushing the update everyday on twitch (see: https://www.curseforge.com/wow/addons/raiderio/files), but it looks like there's an issue currently with the Twitch Client not updating the addon :/ 

If you want you can use the RaiderIO Client to avoid any issue that might occur on twitch : https://raider.io/addon

Isak.
