### ISSUE TITLE
Vexiona HC

### ISSUE THREAD

**Issue by bullshifter** [RaiderIO/raiderio-addon#136]
Hi,

I killed the boss at HC lvl but my Raider.io counted it as Normal kill, can you help, please?

![VEX](https://user-images.githubusercontent.com/69674561/90238307-6a35e400-de2e-11ea-8f28-86162d493dc1.png)

**Comment by jahraphael** [comment]
I see a heroic Vexiona kill on your Raider.IO profile. Maybe you just needed to refresh it?

![image](https://user-images.githubusercontent.com/2944670/90247597-8a4caf80-ddfc-11ea-8a57-cbfb445d4bd5.png)

**Comment by bullshifter** [comment]
Hi,

I did refresh it several times before I worte you, now it’s fixed

Thank you!

**Comment by bullshifter** [comment]
One more thing, yesterday I did +18 see here https://raider.io/characters/eu/twisting-nether/Bullshifter but this is not shown at all
I notice that my IO doesn’t refresh correctly for a week or so, can you check if there is some general problem?

[cid:image002.png@01D6725E.6B8B4570]




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: engin akceli<mailto:engin.akceli@hotmail.com>
Sent: 14 August 2020 17:11
To: RaiderIO/raiderio-addon<mailto:reply@reply.github.com>
Subject: RE: [RaiderIO/raiderio-addon] Vexiona HC (#136)

Hi,

I did refresh it several times before I worte you, now it’s fixed

Thank you!
