### ISSUE TITLE
NEW: not syncing after update. 

### ISSUE THREAD

**Issue by Ognarr** [RaiderIO/raiderio-addon#138]
Issue: RIO score (M+ and Raiding) is not showing updated values, after add-on UPDATE. 

YES: wtf folder deleted
YES: add-on was reinstalled
YES: add-on was deleted, and installed again
YES: manually wiped retail-interface/addons folder + recycle bin
NO: the above helped solve my issue. 

P.S. You must invest more time in the app you wrote; it fails to function properly, timely, and as expected. And no: it must function as expected by simply updating the add-on via Twitch-app = = = without the need to read multiple blogs, using scientific calculator, restarting platforms, trying it on different PCs, waiting for 30 minutes (in case the addon needs time to update...(!)) etc etc for the addon to work. Despicable.

**Comment by Ognarr** [comment]
This just isn't good enough. It's not 2010: 

"
The addon is updated throughout the day. If you are using the Twitch Client then you will only have access to one addon database update per day.

The Raider.IO Desktop client provides more frequent and automated updates to the Raider.IO addon. By default, you will at least be able to update your addon twice per day, but the Desktop Client can provide up 8 updates per day depending on your status.

If you are using the Raider.IO Desktop Client alongside the Twitch Client you will want to ensure that the Twitch Client is set to “Ignore” the Raider.IO Addon, otherwise it may attempt to downgrade the Raider.IO Addon.
"

**Comment by WFrancois** [comment]
Hello to you too ! :) 

Not sure to understand what you are using to update the addon ? Are you using the twitch application, or the raiderio client ?

If you're using the twitch application, we have no way to control how it sends the updates, we only push our files to them. (You can see that we *do* send an updates every day.

If you're updating via the raiderio client, make sure to put the raiderio addon on ignored to make sure twitch doesn't downgrade the version.

(Btw, courtesy is always nice when treating with someone, even though 2020 hasn't been nice with us :) )

**Comment by Ognarr** [comment]
Yeah no I tried all that via raider, not via twitch. 
Just too slow to update anyway. 
KR-




On Friday, 4 September 2020 WFrancois <reply@reply.github.com> wrote:



Hello to you too ! :)

Not sure to understand what you are using to update the addon ? Are you using the twitch application, or the raiderio client ?

If you're using the twitch application, we have no way to control how it sends the updates, we only push our files to them. (You can see that we do send an updates every day.

If you're updating via the raiderio client, make sure to put the raiderio addon on ignored to make sure twitch doesn't downgrade the version.

(Btw, courtesy is always nice when treating with someone, even though 2020 hasn't been nice with us :) )
