### ISSUE TITLE
Raid progress not show

### ISSUE THREAD

**Issue by gaveer** [RaiderIO/raiderio-addon#142]
Hello there , I want to mention with the new raid tier detection and tweaks had some conflict .

i always had ["showRaidEncountersInProfile"] = false, and showing My Raid progress in Tooltips , after the resent update the Raid progress stop showing unless i turn it on settings 

the reason i turn that off cuz the long list off the encounter counts .

**Comment by gaveer** [comment]
@Vladinator89

**Comment by gaveer** [comment]
i revert to v202009170600  and i took the database of **Today**  scores and work

**Comment by gaveer** [comment]
forgot to mention i had Hide personal info **False**

**Comment by gaveer** [comment]
![](https://cdn.discordapp.com/attachments/326736545375584257/759065394069241912/Untitled.jpg)

![](https://cdn.discordapp.com/attachments/326736545375584257/759067753494609920/after.png)

![](https://cdn.discordapp.com/attachments/326736545375584257/759069396537835591/unknown.png)

![](https://cdn.discordapp.com/attachments/326736545375584257/759069438489264149/unknown.png)

**Comment by Vladinator89** [comment]
Thanks for your report. We're looking into previous and current behavior and see if we re-implement it as-is or tweak it a little.

**Comment by gaveer** [comment]
BTW its only show the Nylotha Progress on Self ( even with modifier )
