### ISSUE TITLE
prepatch 9.0.1 errors

### ISSUE THREAD

**Issue by Zetaprime82** [RaiderIO/raiderio-addon#145]
12x RaiderIO\core.lua:3725: attempt to call global 'BNGetFriendInfo' (a nil value)
[string "@RaiderIO\core.lua"]:3725: in function <RaiderIO\core.lua:3718>
[string "=[C]"]: in function `Show'
[string "@FrameXML\FriendsFrame.lua"]:2047: in function <FrameXML\FriendsFrame.lua:1878>

Locals:
self = FriendsTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 backdropBorderColor = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 button = FriendsListFrameScrollFrameButton2 {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 RightEdge = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 Show = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 height = 37.999999
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 0 = <userdata>
 TopEdge = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 maxWidth = 107.999985
 Center = <unnamed> {
 }
 backdropInfo = <table> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 BottomRightCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 backdropColor = <table> {
 }
}
button = FriendsListFrameScrollFrameButton2 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\FriendsFrame.lua:1878
 index = 2
 buttonType = 2
 travelPassButton = FriendsListFrameScrollFrameButton2TravelPassButton {
 }
 status = FriendsListFrameScrollFrameButton2Status {
 }
 background = FriendsListFrameScrollFrameButton2Background {
 }
 OnClick = <function> defined @FrameXML\FriendsFrame.lua:2055
 OnLoad = <function> defined @FrameXML\FriendsFrame.lua:1874
 id = 2
 OnLeave = <function> defined @FrameXML\FriendsFrame.lua:2050
 name = FriendsListFrameScrollFrameButton2Name {
 }
 highlight = <unnamed> {
 }
 summonButton = FriendsListFrameScrollFrameButton2SummonButton {
 }
 info = FriendsListFrameScrollFrameButton2Info {
 }
 Favorite = <unnamed> {
 }
 gameIcon = FriendsListFrameScrollFrameButton2GameIcon {
 }
}
fullName = nil
faction = nil
level = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'BNGetFriendInfo' (a nil value)"
tooltip = <table> {
 index = 9
 Enable = <function> defined @RaiderIO\core.lua:368
 GetDependencies = <function> defined @RaiderIO\core.lua:410
 OnDisable = <function> defined @RaiderIO\core.lua:442
 HasDependencies = <function> defined @RaiderIO\core.lua:393
 OnLoad = <function> defined @RaiderIO\core.lua:3752
 SetLoaded = <function> defined @RaiderIO\core.lua:338
 IsLoaded = <function> defined @RaiderIO\core.lua:358
 enabled = true
 loaded = true
 id = "FriendTooltip"
 OnEnable = <function> defined @RaiderIO\core.lua:438
 Disable = <function> defined @RaiderIO\core.lua:378
 SetDependencies = <function> defined @RaiderIO\core.lua:388
 IsEnabled = <function> defined @RaiderIO\core.lua:363
 SetEnabled = <function> defined @RaiderIO\core.lua:353
 Load = <function> defined @RaiderIO\core.lua:343
 CanLoad = <function> defined @RaiderIO\core.lua:427
}
config = <table> {
 SavedVariablesLoaded = true
 index = 2
 Enable = <function> defined @RaiderIO\core.lua:368
 GetDependencies = <function> defined @RaiderIO\core.lua:410
 Get = <function> defined @AddOns

**Comment by Vladinator89** [comment]
Thanks for the report. It will be fixed in the upcoming addon update cycle. This did sneak past testing on the beta given there are no friends with scores on those test realms.
