### ISSUE TITLE
RaiderIO might conflict with BlizzardChallengesUI 

### ISSUE THREAD

**Issue by gaveer** [RaiderIO/raiderio-addon#146]
prepatch 9.0 
new version 
**Lua error** 
```
100x dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:225: attempt to index field '?' (a nil value)
[string @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:225: in function `ChallengesFrame_Update'
[string @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:134: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:125>
```
**screen shot** from the < Mythic keystone > Tap
![image](https://user-images.githubusercontent.com/45834601/96054381-d6aa7f00-0e81-11eb-8971-bc595f1729cc.png)

**Comment by Vladinator89** [comment]
Thanks for the report. I will take a closer look how the UI behaves now that we are in the pre-patch period.

I believe that the keystone tab is supposed to be grayed out and disabled, because I think Blizzard already kind of wrecked the old dungeon frames for BfA in preparation for SL. In that case there is not much we can do about it. I believe we had a similar issue between Legion and BfA so it might just be the default UI not properly adapting and causing the error.

**Comment by gaveer** [comment]
i tried  **Disable** Raider.IO and no errors or UI bug

**Comment by Vladinator89** [comment]
That is very strange because I see this window. It might be a combination of RIO + another addon that might conflict and cause the errors you are experiencing.

![image](https://user-images.githubusercontent.com/8304135/96184035-29df0900-0f38-11eb-99b7-d2c5cd1ec7f0.png)

**Comment by gaveer** [comment]
```css
28x ...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:225: attempt to index field '?' (a nil value)
[string "@Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:225: in function 'ChallengesFrame_Update'
[string "@Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua"]:134: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:125>

Locals:
self = ChallengesFrame {
 SeasonChangeNoticeFrame = <unnamed> {
 }
 leadersAvailable = false
 maps = <table> {
 }
 Background = <unnamed> {
 }
 DungeonIcons = <table> {
 }
 0 = <userdata>
 WeeklyInfo = <unnamed> {
 }
}
sortedMaps = <table>
hasWeeklyRun = false
weeklySortedMaps = <table>
frameWidth = 549.999939
num = 0
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 1
(*temporary) = ChallengesFrame {
 SeasonChangeNoticeFrame = <unnamed> {
 }
 leadersAvailable = false
 maps = <table> {
 }
 Background = <unnamed> {
 }
 DungeonIcons = <table> {
 }
 0 = <userdata>
 WeeklyInfo = <unnamed> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 549.999939
(*temporary) = 1
(*temporary) = 2
(*temporary) = 2
(*temporary) = 547.999939
(*temporary) = 274.999969
(*temporary) = 547.999939
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = ChallengesFrame {
 SeasonChangeNoticeFrame = <unnamed> {
 }
 leadersAvailable = false
 maps = <table> {
 }
 Background = <unnamed> {
 }
 DungeonIcons = <table> {
 }
 0 = <userdata>
 WeeklyInfo = <unnamed> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = -274.999969
(*temporary) = 5
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
GetRunQualityBasedOnLevel = <function> defined @s\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:16
CreateFrames = <function> defined @s\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:32
LineUpFrames = <function> defined @s\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:83
CHEST_STATE_WALL_OF_TEXT = 1
CHEST_STATE_COLLECT = 4
CHEST_STATE_COMPLETE = 3
CHEST_STATE_INCOMPLETE = 2
```

**Comment by gaveer** [comment]
```cs
[string "@MythicDungeonTools\MythicDungeonTools-3.2.0.lua"]:202: in function <...ace\MythicDungeonTools\MythicDungeonTools.lua:201>
```
and this show up even with **mythicdungeon tool** not loaded

**Comment by Vladinator89** [comment]
I tried to reproduce this but I don't get any errors both without any addons loaded or with RIO loaded, I think there is something else going on that interferes with your game to cause this error. If you unload all addons you should not get these errors. I wonder if you might have to validate game files and see if something weird is going on with your installation.

**Comment by gaveer** [comment]
https://github.com/Gethe/wow-ui-source/blob/1cf759abedf90eaf4adaa1be3629855626c2d998/AddOns/Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua#L134
