### ISSUE TITLE
New server encountered

### ISSUE THREAD

**Issue by Recite77** [RaiderIO/raiderio-addon#149]
Hello, I tried loading up RaiderIO for the first time and received this message:

_RaiderIO has encountered a new server.  Please write down this information [ Player-4714-00ED746C , Thunderfury } and report it to the developers._

I wasn't sure where to post this.  I hope I have the right spot!

Thank you!

**Comment by jahraphael** [comment]
Hi there - this appears to be a Classic server, but Raider.IO only works on live.

We intended to prevent the addon from loading on Classic, so we'll investigate why this isn't working for that server.
