### ISSUE TITLE
RaiderIO\core.lua:1229: attempt to compare nil with number

### ISSUE THREAD

**Issue by zmoose** [RaiderIO/raiderio-addon#150]
14x RaiderIO\core.lua:1229: attempt to compare nil with number
[string "@RaiderIO\core.lua"]:1229: in function `GetScoreColor'
[string "@RaiderIO\core.lua"]:3444: in function `UpdateTooltip'
[string "@RaiderIO\core.lua"]:3032: in function `ShowKeystone'
[string "@RaiderIO\core.lua"]:4882: in function <RaiderIO\core.lua:4866>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:499: in function <...TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:493>
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:98: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96>
[string "@TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua"]:425: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1324: in function `ContainerFrameItemButton_OnUpdate'
[string "@FrameXML\ContainerFrame.lua"]:1371: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:369: in function `ShowTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:340: in function `UpdateTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:180: in function <...faceBagnon\common\Wildpants\classes\item.lua:179>

Locals:
self = <table> {
 IsUnitMaxLevel = <function> defined @RaiderIO\core.lua:1033
 GetLFDStatusForCurrentActivity = <function> defined @RaiderIO\core.lua:1174
 index = 3
 Enable = <function> defined @RaiderIO\core.lua:368
 GetTimeZoneOffset = <function> defined @RaiderIO\core.lua:859
 GetDungeonByLFDActivityID = <function> defined @RaiderIO\core.lua:747
 GetFaction = <function> defined @RaiderIO\core.lua:898
 GetTimeFromDateString = <function> defined @RaiderIO\core.lua:868
 enabled = true
 HasDependencies = <function> defined @RaiderIO\core.lua:393
 GetSortedDungeons = <function> defined @RaiderIO\core.lua:737
 GetRegion = <function> defined @RaiderIO\core.lua:876
 IsLoaded = <function> defined @RaiderIO\core.lua:358
 GetKeystoneChestColor = <function> defined @RaiderIO\core.lua:1250
 SetOwnerSafely = <function> defined @RaiderIO\core.lua:817
 GetKeystoneAverageScoreForLevel = <function> defined @RaiderIO\core.lua:1258
 IsEnabled = <function> defined @RaiderIO\core.lua:363
 GetNameRealm = <function> defined @RaiderIO\core.lua:994
 SetEnabled = <function> defined @RaiderIO\core.lua:353
 Disable = <function> defined @RaiderIO\core.lua:378
 GetScoreColor = <function> defined @RaiderIO\core.lua:1205
 GetFactionFromRace = <function> defined @RaiderIO\core.lua:924
 GetNameRealmFromPlayerLink = <function> defined @RaiderIO\core.lua:1084
 FormatToPattern = <function> defined @RaiderIO\core.lua:838
 loaded = true
 GetInstanceStatus = <function> defined @RaiderIO\core.lua:1166
 GetLFDStatus = <function> defined @RaiderIO\core.lua:1132
 GetDependencies = <function> defined @RaiderIO\core.lua:410
 GetKeystoneLevelFromText = <function> defined @RaiderIO\core.lua:1105
 GetNumChests = <function> defined @RaiderIO\core.lua:1238
 GetDungeonByName = <function> defined @RaiderIO\core.lua:785
 GetDungeonByID = <function> defined @RaiderIO\core.lua:770
 IsUnitPlayer = <function> defined @RaiderIO\core.lua:1044
 GetDungeonByInstanceMapID = <function> defined @RaiderIO\core.lua:775
 IsMaxLevel = <function> defined @RaiderIO\core.lua:1024
 GetDungeonByKeyValue = <function> defined @RaiderIO\core.lua:760
 OnDisable = <function> defined @RaiderIO\core.lua:442
 IsUnitToken = <function> defined @RaiderIO\core.lua:976
 GetRealmSlug = <function> defined @RaiderIO\core.lua:930
 OnLoad = <function> defined @RaiderIO\core.lua:433
 SetLoaded = <function> defined @RaiderIO\core.lua:338
 IsUnit = <function> defined @RaiderIO\core.lua:983
 ExecuteWidgetHandler = <function> defined @RaiderIO\core.lua:797
 GetDungeonByIndex = <function> defined @RaiderIO\core.lua:742
 id = "Util"
 OnEnable = <function> defined @RaiderIO\core.lua:438
 GetDungeonByKeystoneID = <function> defined @RaiderIO\core.lua:780
 SetDependencies = <function> defined @RaiderIO\core.lua:388
 GetNameRealmForBNetFriend = <function> defined @RaiderIO\core.lua:1052
 GetDungeonByShortName = <function> defined @RaiderIO\core.lua:790
 Load = <function> defined @RaiderIO\core.lua:343
 CanLoad = <function> defined @RaiderIO\core.lua:427
}
score = 175
isPreviousSeason = nil
colors = <table> {
 2 = <table> {
 }
 3 = <table> {
 }
 1 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
colorsSimple = <table> {
 2 = <table> {
 }
 3 = <table> {
 }
 1 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
(for

**Comment by Vladinator89** [comment]
Thanks for the report. This bug was tied in with the new season score tiers, some missing data made this error occur, but it was since adjusted and resolved once people got some keystones that made this error occur when hovering the keystone item.
