### ISSUE TITLE
Include covenant to ingame DB-GetProfile data.

### ISSUE THREAD

**Issue by Dinodanio** [RaiderIO/raiderio-addon#155]
Is it possible to include the covenant to your ingame database? There is no functionallity by blizzard to get the covenant of a player by id.

**Comment by WFrancois** [comment]
Heyas!

This was something that was already discussed in our Discord, but it was decided against.
Right now the RaiderIO Addon will continue to only focus on your progression and experience.

Thanks for the suggestion!
Isak.
