### ISSUE TITLE
not seeing my own rio & mouseover tooltip

### ISSUE THREAD

**Issue by bjornenn** [RaiderIO/raiderio-addon#157]
So since today I've not been able to see my own raiderio in the lfg window. I've also been missing mouseover tooltips since start of shadowlands. i've tried reinstalling the addon multiple times, iam running the latest build of the addon.

thanks

**Comment by Vladinator89** [comment]
It sounds like either another addon conflict or oddness with settings. You can always try to reset the RIO settings to defaults using this chat command, as the default options should work. It's worth a try I figure:

```/run wipe(RaiderIO_Config)ReloadUI()```

If it does, I suspect the issue might have been the fixed tooltip anchor frame perhaps being out of screen for some odd reason.

**Comment by bjornenn** [comment]
> 
> 
> It sounds like either another addon conflict or oddness with settings. You can always try to reset the RIO settings to defaults using this chat command, as the default options should work. It's worth a try I figure:
> 
> `/run wipe(RaiderIO_Config)ReloadUI()`
> 
> If it does, I suspect the issue might have been the fixed tooltip anchor frame perhaps being out of screen for some odd reason.

Hey, thanks for the response.

This did indeed resolve all my issues. 

Thank you very much
