### ISSUE TITLE
Sugestion - Show M+ quit ratio

### ISSUE THREAD

**Issue by joaopedromago** [RaiderIO/raiderio-addon#159]
Hello, is it possible to calculate a quit ratio in M ​​+, recording this information in logs and updating it through the raider.io application?

There may be another alternative to do this, but it is an important metric for seeing the quality of a player.

**Comment by WFrancois** [comment]
Heyas!

At the moment, we don't have any solution to have a quit ratio in M+, we don't have this information either in the API, or in the logs.

This is something that we have in our mind, but doing something like that will require a lot of reflection to avoid all edge case.

Thanks for the suggestion!
Isak.
