### ISSUE TITLE
I only get a 1 day old data version 

### ISSUE THREAD

**Issue by Paragalla** [RaiderIO/raiderio-addon#160]
for some reason, i only get the data from the day before by my download with the curse forge (beta) client
is this an github problem or curseforge client problem ?

**Comment by wiiittttt** [comment]
I'm seeing the same issue for the last few days. It seems like the Curseforge API is still showing the previous file after a new one is published.

![latest](https://user-images.githubusercontent.com/5240290/107391887-2400cb00-6ac7-11eb-85e1-6a6b342a52e9.png)

**Comment by WFrancois** [comment]
I'm not sure I understand what the issue is.

Here's the curseforge page https://www.curseforge.com/wow/addons/raiderio/files where we send an update every day.

**Comment by Paragalla** [comment]
Just now i use CurseForge beta to update my RIO datafile. It is 18:xx o clock on feb the 9th and i get offered the file from 202102082225 and not 2021020906xx

![rio](https://user-images.githubusercontent.com/61377157/107400301-fb49f700-6b01-11eb-958b-62415ea79e2d.jpg)

**Comment by Paragalla** [comment]
as far as i can see, it seems that in the last 10 h only 3000 download were performed, although i believe that more than 3000 ppl used the update in CurseForge

![rio2](https://user-images.githubusercontent.com/61377157/107400758-6d224080-6b02-11eb-8f72-2b21de351db4.jpg)

**Comment by WFrancois** [comment]
Hm, yes there's indeed an issue where it might take some time to be sent to the curseforge client. But sadly we can't do anything about that. 

If you want, we have a client where we have more control over the process : https://raider.io/addon.
