### ISSUE TITLE
Key not timed shown as timed after dungeon tweaks

### ISSUE THREAD

**Issue by RicardoAlmeida25** [RaiderIO/raiderio-addon#161]
Hey.
With the recent nerfs to dungeons made by Blizzard, I noticed that there might be a bug on the way the timers are handled.
Before the DoS time nerf to 43 minutes, I did a key that ended up taking 41:21 minutes, a bit overtime at the time. However, since the nerf, it's shown on time on the website and the Raider.IO score has been updated accordingly.
This leads me to believe that the score, or if the key was timed or not, is always calculated again or in a similar fashion, based on the current values, which shouldn't be the case I believe.

Link to the dungeon: https://raider.io/mythic-plus-runs/season-sl-1/16951990-13-de-other-side

**Comment by WFrancois** [comment]
Heyas!

This is expected behavior, all DOS runs are being reprocessed with this new timer.

The score will also need to be reprocessed and everything should be finished in less than 24 hours now.

Thanks for the report though!

Isak.
