### ISSUE TITLE
Can't see my personal RIO but can see the others

### ISSUE THREAD

**Issue by Thomas-VALVERDE** [RaiderIO/raiderio-addon#164]
Since the last version i can't see my RIO, there is aniConflict with Separate Addon Updater Detected, i tryed to delete both and re instal only Raider IO mythic client but seems not working...

Could you please help me ? I tried to uninstall WOW but not seems working too..

**Comment by askdar** [comment]
Такая же проблема и переустановка ничего не дала.

**Comment by WFrancois** [comment]
Heyas!

There was an issue with the data yesterday, this should now be fixed though.

Note: you need to have more than 200 score to be included in the addon.

**Comment by askdar** [comment]
Спасибо,все теперь работает.

**Comment by Tannerd00** [comment]
Hello, I'm having the same problem. Online, on the website, It shows my raider IO score of 1415 for Mythic+... I am able see everyone else's In-game IO scores and progress but they are not able to see mine. It was working fine a couple days ago... My IO client shows my updated score of 1415 just not In-game. People do not take the time to look up IO so if it isn't showing for them... I get instant declined when searching for groups.

What I've done so far to try and fix problem:
1) I uninstalled everything in "Addons" Folder
2) Downloaded Raider.io Client from "Raider.io" website
3) Launched WoW
4) Noticed Same problem re-occuring (I see everyone IO They don't see mine)
5) Closed WoW & Refreshed Client (Now shows my character and new updated IO inside the Client)
6) Launch WoW (Still no In-Game IO. Able to still see others In-game IO)

I was told by some people that It should fix itself with time. I will be back in 24hrs. With good news or bad news. Thanks!

**Comment by WFrancois** [comment]
Heyas!

The issue should get resolve by following these steps : 
![image](https://user-images.githubusercontent.com/5872952/108106023-b2f48100-708d-11eb-941a-bd852ff5c4a5.png)

If not I suggest you to join our discord (https:/discord.gg/raider) and ask in the #support channel :)
