### ISSUE TITLE
Character disappearing fix for people that don't have raider.io account

### ISSUE THREAD

**Issue by Fawniie** [RaiderIO/raiderio-addon#165]
Hello, thank you for making this addon and maintaining it!

I have a question/problem, I've noticed that there were issues yesterday with character scores disappearing. Thankfully you guys found a fix for it, but this fix only works for people that have a Raider.io account, since you have to log in and sync your character form there. 

Is there a way to fix the character disappearing issue for the people that don't have an account? Or will there be one in the future? 

Thank you in advance.

**Comment by jahraphael** [comment]
Hi there, we are working on a fix that should help those that don't have an accounts. No ETA to provide yet, but stay tuned to our Discord or Twitter.
