### ISSUE TITLE
IO bugged/reset, help! :)

### ISSUE THREAD

**Issue by OriginalZasuke** [RaiderIO/raiderio-addon#166]
Hello! Been having an issue with my IO since friday unfortunately. Originally my IO was completely gone and it was if I hadnt dont any m+ runs or raids(I dont care for raiding much honestly) Yesterdays update fixed my raid runs but hadnt updated my m+ until today. Just logged into WoW not to long ago and checked to see if it was up. It was BUT at less then a fraction of my m+ runs are currently documented. I'm at about 40+ 5-9 runs timed and around 8 10 runs completed with around 711 IO, or at least thats what it was thursday evening. It's literally impossible to run keys that I need for progression without an IO especially as a paly. I run prot mainly because no one takes melee for dps and even then DH is what people look for. Have already been held back from completing my vault for the week at a full +10/12s because no respecting team would pick my IO up. Would appreciate some feedback to this either through here or via email. If this isnt the correct place to place this it would be nice if someone could direct me to where to send this. Thank you!

**Comment by OriginalZasuke** [comment]
Still not fixed after update... If I go back to Thursdays version it has my original IO along with all the dungeons completed. Really would like some help in fixes this as Im trying to push 10s/12s this week. Any advice would be appreciated!

**Comment by WFrancois** [comment]
Hey there!

We had an issue this week making run disappear.

Try to follow these steps : 
![image](https://user-images.githubusercontent.com/5872952/108105854-732d9980-708d-11eb-944c-40c395d30692.png)

If not I advise you to join our discord (https://discord.gg/raider) and ask in the #support channel :)
