### ISSUE TITLE
LUA errors generated on group creation 

### ISSUE THREAD

**Issue by rionshin** [RaiderIO/raiderio-addon#178]
22x RaiderIO\core.lua:2898: attempt to compare nil with number
[string "@RaiderIO\core.lua"]:2898: in function `OverrideProfile'
[string "@RaiderIO\core.lua"]:4032: in function <RaiderIO\core.lua:4016>
[string "=[C]"]: ?

Locals:
self = <table> {
 OverrideProfile = <function> defined @RaiderIO\core.lua:2882
 index = 6
 GetProviderByType = <function> defined @RaiderIO\core.lua:1992
 Enable = <function> defined @RaiderIO\core.lua:400
 GetDependencies = <function> defined @RaiderIO\core.lua:442
 GetProviders = <function> defined @RaiderIO\core.lua:1988
 GetProvidersDates = <function> defined @RaiderIO\core.lua:2001
 WipeCache = <function> defined @RaiderIO\core.lua:3096
 GetProfile = <function> defined @RaiderIO\core.lua:3011
 OnDisable = <function> defined @RaiderIO\core.lua:474
 enabled = true
 HasDependencies = <function> defined @RaiderIO\core.lua:425
 OnLoad = <function> defined @RaiderIO\core.lua:1984
 SetLoaded = <function> defined @RaiderIO\core.lua:370
 IsLoaded = <function> defined @RaiderIO\core.lua:390
 AddProvider = <function> defined @RaiderIO\core.lua:2046
 loaded = true
 id = "Provider"
 OnEnable = <function> defined @RaiderIO\core.lua:470
 Disable = <function> defined @RaiderIO\core.lua:410
 SetDependencies = <function> defined @RaiderIO\core.lua:420
 IsEnabled = <function> defined @RaiderIO\core.lua:395
 SetEnabled = <function> defined @RaiderIO\core.lua:385
 Load = <function> defined @RaiderIO\core.lua:375
 CanLoad = <function> defined @RaiderIO\core.lua:459
}
name = "Adí"
realm = "TwistingNether"
faction = 2
overallScore = 2278
keystoneRuns = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
region = "eu"
guid = "eu 2 TwistingNether Adí"
cache = <table> {
 guid = "eu 2 TwistingNether Adí"
 raidProfile = <table> {
 }
 success = true
 faction = 2
 region = "eu"
 name = "Adí"
 realm = "TwistingNether"
}
mythicKeystoneProfile = <table> {
 mplusCurrent = <table> {
 }
 maxDungeonLevel = 0
 sortedMilestones = <table> {
 }
 mplusPrevious = <table> {
 }
 dungeons = <table> {
 }
 sortedDungeons = <table> {
 }
 mplusMainCurrent = <table> {
 }
 mplusMainPrevious = <table> {
 }
 maxDungeonUpgrades = 0
 dungeonTimes = <table> {
 }
 dungeonUpgrades = <table> {
 }
 maxDungeon = 0
}
(*temporary) = nil
(*temporary) = <table> {
 mplusCurrent = <table> {
 }
 maxDungeonLevel = 0
 sortedMilestones = <table> {
 }
 mplusPrevious = <table> {
 }
 dungeons = <table> {
 }
 sortedDungeons = <table> {
 }
 mplusMainCurrent = <table> {
 }
 mplusMainPrevious = <table> {
 }
 maxDungeonUpgrades = 0
 dungeonTimes = <table> {
 }
 dungeonUpgrades = <table> {
 }
 maxDungeon = 0
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
(*temporary) = <function> defined @RaiderIO\core.lua:2410
(*temporary) = <table> {
 dungeon = <table> {
 }
 level = 0
 chests = 0
 fractionalTime = 999
}
(*temporary) = <table> {
 dungeon = <table> {
 }
 level = 0
 chests = 0
 fractionalTime = 999
}
(*temporary) = true
(*temporary) = <table> {
 dungeon = <table> {
 }
 level = 0
 chests = 0
 fractionalTime = 999
}
(*temporary) = <table> {
 dungeon = <table> {
 }
 level = 0
 chests = 0
 fractionalTime = 999
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 999
(*temporary) = 999
(*temporary) = true
(*temporary) = "PF"
(*temporary) = "NW"
(*temporary) = nil
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(*temporary) = <table> {
 Nordrassil = <table> {
 }
 Silvermoon = <table> {
 }
 DerAbyssischeRat = <table> {
 }
 ТкачСмерти = <table> {
 }
 Борейскаятундра = <table> {
 }
 Tyrande = <table> {
 }
 AeriePeak = <table> {
 }
 Mug'thol = <table> {
 }
 Kil'jaeden = <table> {
 }
 Karazhan = <

**Comment by WFrancois** [comment]
Heyas, thanks for the report!

This is fixed in https://github.com/RaiderIO/raiderio-addon/commit/870f9e8217bcff7efa34ed82a5e8a3e11c84289f

A build is coming out soon on curse and the client to fix this :)
