### ISSUE TITLE
[Lua error] core.lua:2898: attempt to compare nil with number

### ISSUE THREAD

**Issue by RavenDT** [RaiderIO/raiderio-addon#179]
Version: 9.1.0 (v202107041304)
```
Message: Interface\AddOns\RaiderIO\core.lua:2898: attempt to compare nil with number
Time: Sun Jul  4 11:05:57 2021
Count: 4
Stack: Interface\AddOns\RaiderIO\core.lua:2898: attempt to compare nil with number

Locals: 
```

**Comment by WFrancois** [comment]
Heyas, thanks for the report!

This is fixed in https://github.com/RaiderIO/raiderio-addon/commit/870f9e8217bcff7efa34ed82a5e8a3e11c84289f

A build is coming out soon on curse and the client to fix this :)
