### ISSUE TITLE
core.lua

### ISSUE THREAD

**Issue by kgwium** [RaiderIO/raiderio-addon#183]
This one just started occurring,  been online most of today and suddenly this error started popping up.
Was in Oribos, can replicate this one over and over again by hovering the mouse pointer over players.

------------------------------------------------------------------------------------------------

16x RaiderIO\core.lua:2898: attempt to index field 'mplusCurrent' (a nil value)
[string "@RaiderIO\core.lua"]:2898: in function `OverrideProfile'
[string "@RaiderIO\core.lua"]:4033: in function <RaiderIO\core.lua:4017>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
self = <table> {
 OverrideProfile = <function> defined @RaiderIO\core.lua:2882
 index = 6
 GetProviderByType = <function> defined @RaiderIO\core.lua:1992
 Enable = <function> defined @RaiderIO\core.lua:400
 GetDependencies = <function> defined @RaiderIO\core.lua:442
 GetProviders = <function> defined @RaiderIO\core.lua:1988
 GetProvidersDates = <function> defined @RaiderIO\core.lua:2001
 WipeCache = <function> defined @RaiderIO\core.lua:3097
 GetProfile = <function> defined @RaiderIO\core.lua:3012
 OnDisable = <function> defined @RaiderIO\core.lua:474
 enabled = true
 HasDependencies = <function> defined @RaiderIO\core.lua:425
 OnLoad = <function> defined @RaiderIO\core.lua:1984
 SetLoaded = <function> defined @RaiderIO\core.lua:370
 IsLoaded = <function> defined @RaiderIO\core.lua:390
 AddProvider = <function> defined @RaiderIO\core.lua:2046
 loaded = true
 id = "Provider"
 OnEnable = <function> defined @RaiderIO\core.lua:470
 Disable = <function> defined @RaiderIO\core.lua:410
 SetDependencies = <function> defined @RaiderIO\core.lua:420
 IsEnabled = <function> defined @RaiderIO\core.lua:395
 SetEnabled = <function> defined @RaiderIO\core.lua:385
 Load = <function> defined @RaiderIO\core.lua:375
 CanLoad = <function> defined @RaiderIO\core.lua:459
}
name = "Dangerbaby"
realm = "Silvermoon"
faction = 1
overallScore = 725
keystoneRuns = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
region = "eu"
guid = "eu 1 Silvermoon Dangerbaby"
cache = <table> {
 guid = "eu 1 Silvermoon Dangerbaby"
 raidProfile = <table> {
 }
 mythicKeystoneProfile = <table> {
 }
 success = true
 faction = 1
 region = "eu"
 name = "Dangerbaby"
 realm = "Silvermoon"
}
mythicKeystoneProfile = <table> {
 hasRenderableData = false
 outdated = 2005
 blocked = true
}
(*temporary) = nil
(*temporary) = "Silvermoon"
(*temporary) = 1
(*temporary) = "eu"
(*temporary) = "eu 1 Silvermoon Dangerbaby"
(*temporary) = <table> {
 guid = "eu 1 Silvermoon Dangerbaby"
 raidProfile = <table> {
 }
 mythicKeystoneProfile = <table> {
 }
 success = true
 faction = 1
 region = "eu"
 name = "Dangerbaby"
 realm = "Silvermoon"
}
(*temporary) = <table> {
 hasRenderableData = false
 outdated = 2005
 blocked = true
}
(*temporary) = <table> {
 hasRenderableData = true
 outdated = 1176
 progress = <table> {
 }
 sortedProgress = <table> {
 }
 previousProgress = <table> {
 }
}
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = 1
(*temporary) = 2
(*temporary) = <table> {
 region = "eu"
 date = "2021-07-17T18:14:39Z"
 data = 2
 previousRaid = <table> {
 }
 currentRaid = <table> {
 }
 outdated = 1176
 name = "RaiderIO_DB_EU_A_R"
 faction = 1
 blocked = true
 db1 = <table> {
 }
 queued = false
 lookup1 = <table> {
 }
}
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(*temporary) = <table> {
 Dragonblight = <table> {
 }
 MarécagedeZangar = <table> {
 }
 DerAbyssischeRat = <table> {
 }
 ТкачСмерти = <table> {
 }
 Борейскаятундра = <table> {
 }
 Tyrande = <table> {
 }
 AeriePeak = <table> {
 }
 Mug'thol = <table> {
 }
 Kil'jaeden = <table> {
 }
 Karazhan = <table> {
 }
 Frostwolf = <table> {
 }
 ВечнаяПесня = <table> {
 }
 ScarshieldLegion = <table> {
 }
 KultderVerdammten = <table> {
 }
 Taerar = <table> {
 }
 Ysondre = <table> {
 }
 Deathwing = <table> {
 }
 Gilneas = <table> {
 }
 Agamaggan = <table> {
 }
 DieAldor = <table> {
 }
 Stormrage = <table> {
 }
 Разувий = <table> {
 }
 Sanguino = <table> {
 }
 AzjolNerub = <table> {
 }
 Terrordar = <table> {
 }
 Trollbane = <table> {
 }
 Nethersturm = <table> {
 }
 DieNachtwache = <table> {
 }
 Spinebreaker = <table> {
 }
 Sinstralis = <table> {
 }
 Executus = <

**Comment by Vladinator89** [comment]
It should be resolved with the update a day ago.
