### ISSUE TITLE
error scan player

### ISSUE THREAD

**Issue by Precurseurs** [RaiderIO/raiderio-addon#184]
Message: Interface\AddOns\RaiderIO\core.lua:2898: attempt to index field 'mplusCurrent' (a nil value)
Time: Mon Aug  2 13:12:36 2021
Count: 26
Stack: Interface\AddOns\RaiderIO\core.lua:2898: attempt to index field 'mplusCurrent' (a nil value)
[string "@Interface\AddOns\RaiderIO\core.lua"]:2898: in function `OverrideProfile'
[string "@Interface\AddOns\RaiderIO\core.lua"]:4033: in function <Interface\AddOns\RaiderIO\core.lua:4017>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals: self = <table> {
 OverrideProfile = <function> defined @Interface\AddOns\RaiderIO\core.lua:2882
 index = 6
 GetProviderByType = <function> defined @Interface\AddOns\RaiderIO\core.lua:1992
 Enable = <function> defined @Interface\AddOns\RaiderIO\core.lua:400
 GetDependencies = <function> defined @Interface\AddOns\RaiderIO\core.lua:442
 GetProviders = <function> defined @Interface\AddOns\RaiderIO\core.lua:1988
 GetProvidersDates = <function> defined @Interface\AddOns\RaiderIO\core.lua:2001
 WipeCache = <function> defined @Interface\AddOns\RaiderIO\core.lua:3097
 GetProfile = <function> defined @Interface\AddOns\RaiderIO\core.lua:3012
 OnDisable = <function> defined @Interface\AddOns\RaiderIO\core.lua:474
 enabled = true
 HasDependencies = <function> defined @Interface\AddOns\RaiderIO\core.lua:425
 OnLoad = <function> defined @Interface\AddOns\RaiderIO\core.lua:1984
 SetLoaded = <function> defined @Interface\AddOns\RaiderIO\core.lua:370
 IsLoaded = <function> defined @Interface\AddOns\RaiderIO\core.lua:390
 AddProvider = <function> defined @Interface\AddOns\RaiderIO\core.lua:2046
 loaded = true
 id = "Provider"
 OnEnable = <function> defined @Interface\AddOns\RaiderIO\core.lua:470
 Disable = <function> defined @Interface\AddOns\RaiderIO\core.lua:410
 SetDependencies = <function> defined @Interface\AddOns\RaiderIO\core.lua:420
 IsEnabled = <function> defined @Interface\AddOns\RaiderIO\core.lua:395
 SetEnabled = <function> defined @Interface\AddOns\RaiderIO\core.lua:385
 Load = <function> defined @Interface\AddOns\RaiderIO\core.lua:375
 CanLoad = <function> defined @Interface\AddOns\RaiderIO\core.lua:459
}
name = "Eikitchi"
realm = "Illidan"
faction = 2
overallScore = 1637
keystoneRuns = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
region = "eu"
guid = "eu 2 Illidan Eikitchi"
cache = <table> {
 guid = "eu 2 Illidan Eikitchi"
 raidProfile = <table> {
 }
 mythicKeystoneProfile = <table> {
 }
 success = true
 faction = 2
 region = "eu"
 name = "Eikitchi"
 realm = "Illidan"
}
mythicKeystoneProfile = <table> {
 hasRenderableData = false
 outdated = 16740
 blocked = true
}
(*temporary) = nil
(*temporary) = "Illidan"
(*temporary) = 2
(*temporary) = "eu"
(*temporary) = "eu 2 Illidan Eikitchi"
(*temporary) = <table> {
 guid = "eu 2 Illidan Eikitchi"
 raidProfile = <table> {
 }
 mythicKeystoneProfile = <table> {
 }
 success = true
 faction = 2
 region = "eu"
 name = "Eikitchi"
 realm = "Illidan"
}
(*temporary) = true
(*temporary) = " "
(*temporary) = "Illidan"
(*temporary) = " "
(*temporary) = "Eikitchi"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'mplusCurrent' (a nil value)"
ns = <table> {
 CLIENT_CONFIG = <table> {
 }
 previousScoreTiersSimple = <table> {
 }
 NewModule = <function> defined @Interface\AddOns\RaiderIO\core.lua:479
 GetRegionData = <function> defined @Interface\AddOns\RaiderIO\core.lua:294
 EXPANSION = 7
 realmSlugs = <table> {
 }
 GetModules = <function> defined @Interface\AddOns\RaiderIO\core.lua:509
 PROVIDER_DATA_TYPE = <table> {
 }
 OUTDATED_BLOCK_CUTOFF

**Comment by Vladinator89** [comment]
It should be resolved with the update a day ago.
