### ISSUE TITLE
WHen open - Raid-Shadowlands i get this error 

### ISSUE THREAD

**Issue by devil81** [RaiderIO/raiderio-addon#197]
Message: [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'GetPlaystyleString()'.
Time: Thu Nov 25 21:31:04 2021
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface\FrameXML\LFGList.lua"]:3508: in function <Interface\FrameXML\LFGList.lua:3499>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface\FrameXML\LFGList.lua"]:2576: in function <Interface\FrameXML\LFGList.lua:2573>
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\RaiderIO\core.lua"]:1015: in function `ExecuteWidgetHandler'
[string "@Interface\AddOns\RaiderIO\core.lua"]:5799: in function <Interface\AddOns\RaiderIO\core.lua:5794>
[string "=[C]"]: in function `Update'
[string "@Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua"]:382: in function `UpdateMemberList'
[string "@Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua"]:485: in function <...ddOns\Blizzard_Communities\CommunitiesMemberList.lua:478>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2867: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:3483: in function `ToggleFrame'
[string "@Interface\FrameXML\UIParent.lua"]:1078: in function `ToggleCommunitiesFrame'
[string "@Interface\FrameXML\UIParent.lua"]:932: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals: <none>

**Comment by Vladinator89** [comment]
It's been a while now, but the code in RIO was changed to accommodate with the 9.1.5 changes that caused this error.
