### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Naik93** [RaiderIO/raiderio-addon#199]
i keep get this error every time i open the reserch for a group

> Message: ...AddOns\AddOnSkins\Skins\Mainline\AddOns\RaiderIO.lua:16: attempt to index field 'RaiderIOProfileTooltip' (a nil value)
Time: Sun Jan 30 23:00:59 2022
Count: 1
Stack: ...AddOns\AddOnSkins\Skins\Mainline\AddOns\RaiderIO.lua:16: attempt to index field 'RaiderIOProfileTooltip' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\AddOnSkins\Skins\Mainline\AddOns\RaiderIO.lua"]:16: in function <...AddOns\AddOnSkins\Skins\Mainline\AddOns\RaiderIO.lua:15>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2803: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\PVEFrame.lua"]:130: in function `PVEFrame_ShowFrame'
[string "@Interface\FrameXML\PVEFrame.lua"]:88: in function <Interface\FrameXML\PVEFrame.lua:64>
[string "=[C]"]: in function `PVEFrame_ToggleFrame'
[string "TOGGLEGROUPFINDER"]:1: in function <[string "TOGGLEGROUPFINDER"]:1>

Locals:

**Comment by Vladinator** [comment]
Due to changes in RaiderIO, the addon AddOnSkins needs to update its code, so the error does mention RaiderIO but the issue lies in that AddOnSkins needs an update, then this particular error will go away.
