### ISSUE TITLE
Empty list on LFG - Blizzard

### ISSUE THREAD

**Issue by Yotto89** [RaiderIO/raiderio-addon#201]
I have this issue, 

I try to check ppl on my queu while queuing mythic plus and once a second person gets in queu i cannot see anyone else queuing, Could someone debug or try to solve this issue please? 

5x [string "Error in: Dungeon RIO and Class':'initializ..."]:3: attempt to index global 'RaiderIO' (a nil value)
[string "Error in: Dungeon RIO and Class':'initialization"]:3: in function <[string "Error in: Dungeon RIO and Class':'initializ..."]:1>
[string "Error in: Dungeon RIO and Class':'initialization"]:307: in function <[string "Error in: Dungeon RIO and Class':'initializ..."]:288>
[string "=[C]"]: in function sort'
[string "Error in: Dungeon RIO and Class':'initialization"]:341: in function <[string "Error in: Dungeon RIO and Class':'initializ..."]:281>
[string "=[C]"]: in function LFGListUtil_SortApplicants'
[string "@FrameXML\LFGList.lua"]:1498: in function LFGListApplicationViewer_UpdateResultList'
[string "@FrameXML\LFGList.lua"]:1315: in function onEvent'
[string "@FrameXML\LFGList.lua"]:215: in function <FrameXML\LFGList.lua:136>
[string "=[C]"]: in function RefreshApplicants'
[string "@FrameXML\LFGList.lua"]:1337: in function <FrameXML\LFGList.lua:1336>
[string "=[C]"]: in function Show'
[string "@FrameXML\PVEFrame.lua"]:315: in function `GroupFinderFrame_ShowGroupFrame'
[string "@FrameXML\PVEFrame.lua"]:335: in function <FrameXML\PVEFrame.lua:333>

Locals:
fullname = "Kørpiklaani-Draenor"
score = 0
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = nil
(temporary) = "attempt to index global 'RaiderIO' (a nil value)"

**Comment by Vladinator** [comment]
I realize this is a very old issue, but I just realized going over the issues, that this one is caused by a WeakAura by the name `Dungeon RIO and Class` and it happened because RaiderIO had some changes that other addons and code had to update on their end to continue functioning properly. I hope you got an updated aura by now and resolved the issue.
