### ISSUE TITLE
Tazavesh

### ISSUE THREAD

**Issue by xKukkai** [RaiderIO/raiderio-addon#209]
Hi,

I found 2 bugs with mythic key Tazavesh:
- Streets and Gambit are not displayed in "Record Raider.io - Guild: top week". The line is empty.
Screenshot: https://ibb.co/ssfYKsk

- You can only see "Streets" and not Gambit when your mouse is on a player (or even when you tag for Gambit, in the pop-up, it's Streets that is shown and not Gambit)
EDIT: it seems fixed, to be confirmed. :-)

Have a nice day.
Kukkai

**Comment by jahraphael** [comment]
Thanks for the report. Closing as fixed.
