### ISSUE TITLE
Iron Docks and Grimrail Depot scores are swapped

### ISSUE THREAD

**Issue by benhamlin** [RaiderIO/raiderio-addon#217]
In the personal raiderio tooltip, the best run by dungeon is showing my GD run as ID, and vice versa, presumably in other places as well.

**Comment by benhamlin** [comment]
This appears to have corrected itself after a /reload, or I'm crazy.

**Comment by jahraphael** [comment]
I do think there is a problem, but should be fixed from a commit I just made. We'll kick off another build soon, which should have it fixed in an hour or two.
