### ISSUE TITLE
DF errors 

### ISSUE THREAD

**Issue by kingreboot** [RaiderIO/raiderio-addon#227]
Been getting errors even after updates.

258x Interface/AddOns/RaiderIO/core.lua:7782: attempt to call method 'RegisterEvent' (a nil value)
[string "@Interface/AddOns/RaiderIO/core.lua"]:7782: in function `OnLoad'
[string "@Interface/AddOns/RaiderIO/core.lua"]:715: in function `Load'
[string "@Interface/AddOns/RaiderIO/core.lua"]:4033: in function <Interface/AddOns/RaiderIO/core.lua:4025>
[string "@Interface/AddOns/RaiderIO/core.lua"]:4065: in function `callbackFunc'
[string "@Interface/AddOns/RaiderIO/core.lua"]:950: in function `SendEvent'
[string "@Interface/AddOns/RaiderIO/core.lua"]:885: in function <Interface/AddOns/RaiderIO/core.lua:881>

Locals:
self = <table> {
 index = 19
 Enable = <function> defined @Interface/AddOns/RaiderIO/core.lua:735
 GetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:777
 OnDisable = <function> defined @Interface/AddOns/RaiderIO/core.lua:809
 HasDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:760
 OnLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:7754
 SetLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:705
 IsLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:725
 enabled = true
 loaded = true
 id = "DropDown"
 OnEnable = <function> defined @Interface/AddOns/RaiderIO/core.lua:805
 Disable = <function> defined @Interface/AddOns/RaiderIO/core.lua:745
 SetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:755
 IsEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:730
 SetEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:720
 Load = <function> defined @Interface/AddOns/RaiderIO/core.lua:710
 CanLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:7750
}
(*temporary) = nil
(*temporary) = <table> {
 _callbacks = <table> {
 }
 _cdropdowns = <table> {
 }
}
(*temporary) = "OnShow OnHide"
(*temporary) = <function> defined @Interface/AddOns/RaiderIO/core.lua:7691
(*temporary) = 1
(*temporary) = <table> {
 index = 19
 Enable = <function> defined @Interface/AddOns/RaiderIO/core.lua:735
 GetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:777
 OnDisable = <function> defined @Interface/AddOns/RaiderIO/core.lua:809
 HasDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:760
 OnLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:7754
 SetLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:705
 IsLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:725
 enabled = true
 loaded = true
 id = "DropDown"
 OnEnable = <function> defined @Interface/AddOns/RaiderIO/core.lua:805
 Disable = <function> defined @Interface/AddOns/RaiderIO/core.lua:745
 SetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:755
 IsEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:730
 SetEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:720
 Load = <function> defined @Interface/AddOns/RaiderIO/core.lua:710
 CanLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:7750
}
(*temporary) = "attempt to call method 'RegisterEvent' (a nil value)"
unitOptions = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
L = <table> {
 SHOW_LEADER_PROFILE = "Allow Raider.IO Profile Tooltip Modifier"
 RAID_BOSS_FSFO_1 = "Vigilant Guardian"
 ENABLE_AUTO_FRAME_POSITION = "Position Raider.IO Profile Frame Automatically"
 INVERSE_PROFILE_MODIFIER = "Invert Raider.IO Profile Tooltip Modifier"
 DUNGEON_SHORT_NAME_SD = "SD"
 UNLOCKING_PROFILE_FRAME = "Raider.IO: Unlocking the M+ Profile Frame."
 DB_MODULES_HEADER_MYTHIC_PLUS = "Mythic+"
 GUILD_LF_PVP = "Recruiting PvP Players"
 DUNGEON_SHORT_NAME_PF = "PF"
 RAID_BOSS_FCN_5 = "Sun King's Salvation"
 ENABLE_NO_SCORE_COLORS = "Disable All Mythic+ Score Colors"
 PROFILE_TOOLTIP_ANCHOR_TOOLTIP = "Lock Raider.IO Profile Frame or enable Automatic Positioning in order to hide this anchor."
 CURRENT_MAINS_SCORE = "Main's Current M+ Score"
 RAID_DIFFICULTY_NAME_MYTHIC = "Mythic"
 RAID_BOSS_FCN_10 = "Sire Denathrius"
 DUNGEON_SHORT_NAME_HOA = "HOA"
 RAIDERIO_MP_SCORE = "Raider.IO M+ Score"
 ENABLE_SIMPLE_SCORE_COLORS = "Use Simple Mythic+ Score Colors"
 SHOW_SCORE_IN_COMBAT_DESC = "Disable to minimize performance impact while hovering players during combat."
 COPY_RAIDERIO_PROFILE_URL = "Copy Raider.IO URL"
 CANCEL = "Cancel"
 CHARACTER_LF_GUILD_SOCIAL = "Looking for Social Guild"
 SHOW_CURRENT_SEASON_DESC = "Shows the player's current Mythic+ season score as the tooltip headline."
 TIMED_20_RUNS = "Timed 20+ Runs"
 RAID_BOSS_FSFO_8 = "Anduin Wrynn"
 TIMED_15_RUNS = "Timed 15+ Runs"
 ALLOW_IN_LFD = "Allow in Dungeon Finder"
 SHOW_RAIDERIO_PROFILE = "Show Raider.IO Profile Tooltip"
 COPY_RAIDERIO_RECRUITMENT_U

**Comment by Vladinator** [comment]
This is a very strange error, because what it says is that it failed to run code that, at that point, we expect to be runnable.

I have to ask, since sometimes we update again or restart the game and suddenly something like this goes away, but since the issue is open I wanted to ask if you still have the error occur on your end.

If you still have the error, and have tried to re-install the RaiderIO addon just to see if it helped (or update it as that also would do the trick), could you send me your list of addons that you play with? I could see if something odd is going on from code located in another addon affecting your situation.

I can recommend just test without any addons, other than RaiderIO, just to see if the issue stays or goes away, as an addon or a specific WeakAura could technically be involved causing this error as well.

**Comment by kingreboot** [comment]
I will check after work today

**Comment by kingreboot** [comment]
Either Raider.IO had an update, or whatever addon had issues with got updated, but this is the first time turning on the addon after a few days and no errors. Will update if they come back. Thanks for reaching out

**Comment by Vladinator** [comment]
I'm glad, because it was a very strange error to get in the first place.
