### ISSUE TITLE
attempt to index global 'WhoListScrollFrame' (a nil value)

### ISSUE THREAD

**Issue by matt-storr** [RaiderIO/raiderio-addon#229]
1x Interface/AddOns/RaiderIO/core.lua:5240: attempt to index global 'WhoListScrollFrame' (a nil value)
[string "@Interface/AddOns/RaiderIO/core.lua"]:5240: in function `OnLoad'
[string "@Interface/AddOns/RaiderIO/core.lua"]:601: in function `Load'
[string "@Interface/AddOns/RaiderIO/core.lua"]:3912: in function <Interface/AddOns/RaiderIO/core.lua:3904>
[string "@Interface/AddOns/RaiderIO/core.lua"]:3944: in function `callbackFunc'
[string "@Interface/AddOns/RaiderIO/core.lua"]:836: in function `SendEvent'
[string "@Interface/AddOns/RaiderIO/core.lua"]:771: in function <Interface/AddOns/RaiderIO/core.lua:767>

Locals:
self = <table> {
 index = 9
 Enable = <function> defined @Interface/AddOns/RaiderIO/core.lua:621
 GetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:663
 OnDisable = <function> defined @Interface/AddOns/RaiderIO/core.lua:695
 HasDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:646
 OnLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:5238
 SetLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:591
 IsLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:611
 enabled = true
 loaded = true
 id = "WhoTooltip"
 OnEnable = <function> defined @Interface/AddOns/RaiderIO/core.lua:691
 Disable = <function> defined @Interface/AddOns/RaiderIO/core.lua:631
 SetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:641
 IsEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:616
 SetEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:606
 Load = <function> defined @Interface/AddOns/RaiderIO/core.lua:596
 CanLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:680
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = true
(*temporary) = <table> {
 index = 9
 Enable = <function> defined @Interface/AddOns/RaiderIO/core.lua:621
 GetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:663
 OnDisable = <function> defined @Interface/AddOns/RaiderIO/core.lua:695
 HasDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:646
 OnLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:5238
 SetLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:591
 IsLoaded = <function> defined @Interface/AddOns/RaiderIO/core.lua:611
 enabled = true
 loaded = true
 id = "WhoTooltip"
 OnEnable = <function> defined @Interface/AddOns/RaiderIO/core.lua:691
 Disable = <function> defined @Interface/AddOns/RaiderIO/core.lua:631
 SetDependencies = <function> defined @Interface/AddOns/RaiderIO/core.lua:641
 IsEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:616
 SetEnabled = <function> defined @Interface/AddOns/RaiderIO/core.lua:606
 Load = <function> defined @Interface/AddOns/RaiderIO/core.lua:596
 CanLoad = <function> defined @Interface/AddOns/RaiderIO/core.lua:680
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WhoListScrollFrame' (a nil value)"
OnEnter = <function> defined @Interface/AddOns/RaiderIO/core.lua:5206
OnLeave = <function> defined @Interface/AddOns/RaiderIO/core.lua:5223
OnScroll = <function> defined @Interface/AddOns/RaiderIO/core.lua:5230

**Comment by Vladinator** [comment]
Based on the error, it appears you are using a bit older version of the addon, that doesn't contain the 10.0.0 patch changes.

If you update the addon it should get rid of this message for you. Just ensure you update using the latest regular release, and not a alpha or beta version, those can right now be some weeks or months old as they aren't frequent.
