### ISSUE TITLE
Click on mythic keystone link in chat causes lag

### ISSUE THREAD

**Issue by Neischa** [RaiderIO/raiderio-addon#230]
Hi, as I stated in name of the ticket, when I click on keystone link in chat, it causes about half second lag/freeze. I disabled all other addons, reinstalled RaiderIO (also removed .wtf files), but the issue persisted. This issue is caused by option called "Show Base Raider.IO Score for Keystones". I am not sure if this is a bug or not, but I don't remember this behavior from the past so wanted to ask. Thanks!

**Comment by Vladinator** [comment]
This was an issue we found and fixed a while ago, sorry about it. Closing the ticket since it's resolved.
