### ISSUE TITLE
M+ flyout mixes up AA and RLP scores

### ISSUE THREAD

**Issue by benhamlin** [RaiderIO/raiderio-addon#233]
I have not yet done Algeth'ar Academy, and I have a over-time +10 Ruby Life Pool. However the flyout is showing RLP as never run and AA with a grayed-out 10.

This is data from yesterday, so it's coming from the daily update. 

The data shows correctly on my armory page and on raider.io website.

**Comment by benhamlin** [comment]
Fixed in today's update, presumably the issue was in the data? Closing this.

**Comment by jahraphael** [comment]
There was a bug we addressed yesterday where some of the dungeons were misordered.
