### ISSUE TITLE
The new realm Krol Blade (克羅之刃) is missing in the database

### ISSUE THREAD

**Issue by zfxcis** [RaiderIO/raiderio-addon#240]
In the file db/db_regions.lua, there is no data for server Krol Blade (TW). The server ID is 5735, so it must be manually added the following line to make it work:

[5735] = 4

**Comment by jahraphael** [comment]
Thanks, we have updated this. And have also added Old Blanchy (TW).

This should be reflected in future builds.

**Comment by zfxcis** [comment]
Thanks. These 2 shall be TW (4) not CN (5):

[5735] = 5,
[5736] = 5
