### ISSUE TITLE
Krol Blade & Old Blanchy

### ISSUE THREAD

**Issue by zfxcis** [RaiderIO/raiderio-addon#241]
Hi, glad you add these 2 in the db_regions.lua. But they are all TW (4) not CN (5), just one more step to make it work ;-)

[5735]
[5736]

**Comment by zfxcis** [comment]
It shall be:
[5735] = 4，
[5736] = 4

**Comment by jahraphael** [comment]
😞 

Good catch. This is now updated and should start getting included in subsequent builds.
