### ISSUE TITLE
Dungeon short names for Dawn of the Infinite

### ISSUE THREAD

**Issue by 0xbs** [RaiderIO/raiderio-addon#245]
I'm the author of the popular addon Premade Groups Filter and would like to give it another try to align the dungeon short names before the next mythic plus season starts as it will most likely contain the new dungeons.

My suggestion:

| Dungeon | Short Name |
|-----------|---------------|
| Dawn of the Infinite | DOTI |
| Dawn of the Infinite: Galakrond's Fall | GALA |
| Dawn of the Infinite: Murozond's Rise | MURO |

Feel free to tell me your suggestion.

**Comment by jahraphael** [comment]
Hey there!

On our side we'll only have the split sides for when the dungeon goes to M+.

We've been discussing internally and think the abbreviations that make sense to use are:

Dawn of the Infinite: Galakrond's Fall = `FALL`
Dawn of the Infinite: Murozond's Rise = `RISE`

Would those abbreviations work for PGF as well?

**Comment by 0xbs** [comment]
Yes, of course. I already thought about `RISE` and `FALL` as well. Then I will go with these abbreviations. Thank you for the quick coordination!

**Comment by jahraphael** [comment]
Great! Thanks for reaching out on this.
