### ISSUE TITLE
lua error in dungeon when mouseover player

### ISSUE THREAD

**Issue by DockieB** [RaiderIO/raiderio-addon#251]
I'm receiving multiple lua errors in dungeons every time my mouse hovers over another player. NPCs/mobs/bosses not affected.

291x RaiderIO/core.lua:4853: attempt to compare number with nil
[string "@RaiderIO/core.lua"]:4853: in function <RaiderIO/core.lua:4844>
[string "@RaiderIO/core.lua"]:4890: in function <RaiderIO/core.lua:4870>
[string "@RaiderIO/core.lua"]:5288: in function `UpdateTooltip'
[string "@RaiderIO/core.lua"]:4775: in function `ShowProfile'
[string "@RaiderIO/core.lua"]:5559: in function <RaiderIO/core.lua:5542>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:1092: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1497: in function <FrameXML/UIParent.lua:1420>

Locals:
bestDungeon = nil
bestLevel = 0
bestChests = 0
args = <table> {
 1 = <table> {
 }
 4 = <table> {
 }
}
(for index) = 1
(for limit) = 1
(for step) = 3
i = 1
dungeon = <table> {
 timers = <table> {
 }
 index = 15
 id = 14063
 keystone_instance = 399
 instance_map_id = 2521
 name = "Ruby Life Pools"
 shortName = "RLP"
 lfd_activity_ids = <table> {
 }
 type = "EXPANSION"
}
level = nil
chests = nil
(*temporary) = 399
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by Vladinator** [comment]
Thanks for the info, I suspect this might be due to a change in the addon code, that leaked out from yesterday with this bug, but then I should have gotten this fixed yesterday, and that change should propagate through today.

If you do update the addon and try to hover over yourself in a Dragonflight dungeon, that is not part of the season dungeons (like your Ruby Life Pools), it should no longer error.

But let me know if it's fine or if you still get an error like this, just remember to grab the latest update from today before testing.

Thanks.

**Comment by DockieB** [comment]
I was just able to test it. Works perfectly! Thanks!
