### ISSUE TITLE
M+ Dungeon "short names", in advance?

### ISSUE THREAD

**Issue by joedrago** [RaiderIO/raiderio-addon#254]
(very low priority)

Hi R.io Team -- 

Every season you guys update `db_dungeons.lua` to have a `shortName` associated with each current dungeon, and for various WeakAuras and other tracking I maintain I make an effort to use whatever short names raider.io chooses so the mod UIs are all using the same terms. 

Is there any place other than `db_dungeons.lua` (or running the Addon for the first day tomorrow) where I can get a hint as to the chosen `shortName`s for Season 3? I'd love to update things in advance to hit the ground running. 

Thanks again!

**Comment by jahraphael** [comment]
You can access this data via our API from the "Mythic Plus Static Data" route:

https://raider.io/api/v1/mythic-plus/static-data?expansion_id=9

Hope this helps!
