### ISSUE TITLE
Extra text?

### ISSUE THREAD

**Issue by Milky063** [RaiderIO/raiderio-addon#258]
near best run it has the servers and name of dungeon code in text. this looks like a bug and needs to be removed. 

![image](https://github.com/RaiderIO/raiderio-addon/assets/50210970/70016fcc-687e-468a-ab1c-fc85d690dd29)

**Comment by Yoriichi24** [comment]
Same issue, all text is displayed like this and getting some lua errors when hovering mouse on group finder players scores

**Comment by okanmazman** [comment]
it seems **~/RaiderIO/locale** folder which consist of resource files has no defitinions for this keys for languages supported.
I guess you can add then manually if you desire **until they fix it**..   i.e.   open Interface\AddOns\RaiderIO\locale\enUS.lua file in a text editor, and add like `L.DUNGEON_SHORT_NAME_AD="AD"`  and  run `/reload` script in the game.

**Comment by walialu** [comment]
Same issue here. Weird that Curseforge Mods didn't catch these missing translation keys; when reviewing the addon 🤷

**Comment by radumalica** [comment]
just copy enUS.lua from locale which is updated here to your raider.io addon same location, then reload the game. The repo is updated but they didn't build the release yet which goes to the raider.io windows client and curseforge. other workaround is in addon settings to check the box with "apply US short names" or similar (can't remember).

**Comment by LK-Webservices** [comment]
They fixed it like 15 minutes ago. Just update the addon again. :)

**Comment by WFrancois** [comment]
Hey!

Sorry about that yeah, we were missing some text, this is now resolved
