### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [RaiderIO/raiderio-addon#263]
67x [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'RaiderIO_ProfileTooltipAnchor:EnableMouse()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `EnableMouse'
[string "@RaiderIO/core.lua"]:6445: in function <RaiderIO/core.lua:6444>
[string "@RaiderIO/core.lua"]:6461: in function <RaiderIO/core.lua:6453>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:391: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:1092: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1484: in function <FrameXML/UIParent.lua:1407>

Locals:
Skipped (In Encounter)

**Comment by jahraphael** [comment]
This is an old ticket we expect is no longer happening. If you're still having issues please re-open just a single ticket for it to be tracked in.
