### ISSUE TITLE
Database Refresh failed to publish

### ISSUE THREAD

**Issue by jmsundar** [RaiderIO/raiderio-addon#264]
The last 2 days' Database Refresh action failed to publish a new release:

https://github.com/RaiderIO/raiderio-addon/actions/runs/7206926156

https://github.com/RaiderIO/raiderio-addon/actions/runs/7193349769

The error for both is:

```
Creating GitHub release: https://github.com/RaiderIO/raiderio-addon/releases/tag/v202312130600
Error! (403)
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/releases/releases#create-a-release"
}
```

**Comment by WFrancois** [comment]
Hey, yeah sorry about that.
It was fixed in the latest build! :)
