### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Milky063** [RaiderIO/raiderio-addon#266]
11x [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'RaiderIO_ProfileTooltipAnchor:EnableMouse()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `EnableMouse'
[string "@RaiderIO/core.lua"]:6448: in function <RaiderIO/core.lua:6447>
[string "@RaiderIO/core.lua"]:6464: in function <RaiderIO/core.lua:6456>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetOwner'
[string "@FrameXML/GameTooltip.lua"]:274: in function <FrameXML/GameTooltip.lua:273>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2323: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2319>
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1199: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1197>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by jahraphael** [comment]
This is an old ticket we expect is no longer happening. If you're still having issues please re-open just a single ticket for it to be tracked in.
