### ISSUE TITLE
[Closed] Locale name

### ISSUE THREAD

**Issue by Zerawan2042** [RaiderIO/raiderio-addon#271]
Hi

Could you add an option to choose local name of dungeon because french name are awful and prefer english like lot of my mate

**Comment by xKukkai** [comment]
Hey, 

I sent an email to the RaiderIO team regarding my thread (posted just after yours), and they informed me that there is already an option to force the name in English (which is much better than in French). (see screenshot below)

![RIO](https://github.com/RaiderIO/raiderio-addon/assets/101919309/6bb72073-ba06-4757-bf25-437dc8d27b98)

Have a nice day
Kukkai-MarécageDeZangar

**Comment by Zerawan2042** [comment]
Merci Kukkai-MarécageDeZangar
