### ISSUE TITLE
rio error

### ISSUE THREAD

**Issue by Mithras2801** [RaiderIO/raiderio-addon#277]
5x [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'RaiderIO_ProfileTooltipAnchor:EnableMouse()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `EnableMouse'
[string "@RaiderIO/core.lua"]:6456: in function <RaiderIO/core.lua:6455>
[string "@RaiderIO/core.lua"]:6472: in function <RaiderIO/core.lua:6464>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:391: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "@LUI/api/oUF11/elements/auras.lua"]:82: in function `UpdateTooltip'
[string "@LUI/api/oUF11/elements/auras.lua"]:93: in function <LUI/api/oUF11/elements/auras.lua:86>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511

**Comment by jahraphael** [comment]
This is an old ticket we expect is no longer happening. If you're still having issues please re-open a ticket for it to be tracked in.
