### ISSUE TITLE
Enhancement Request :: Add to Blizzard UI "Add Ons" "Button" (now refers to PR 291)

### ISSUE THREAD

**Issue by JPEscher** [RaiderIO/raiderio-addon#287]
hoping this isn't hard, but i do not see this in the add ons area shown below. i like to use that for a cleaner ui.
![image](https://github.com/RaiderIO/raiderio-addon/assets/46279739/297b8df5-2b5a-493b-942c-bb94372b8bd2)

**Comment by JPEscher** [comment]
notice this in discussion with another add on i use. hope it is helpful
https://warcraft.wiki.gg/wiki/Addon_compartment

**Comment by JPEscher** [comment]
from that, this in "core.lua" causes the button in the addons. im not sure from the code how to get the two interfaces.
```
AddonCompartmentFrame:RegisterAddon({
	text = "Raider.IO Mythic Plus, Raiding, and Recruitment",
	icon = "Interface/AddOns/RaiderIO/icons/logo.blp",
	notCheckable = true,
	func = function(button, menuInputData, menu)
		local buttonName = menuInputData.buttonName;  -- debugging check line
		-- print("Hello from the addon compartment! You clicked " .. buttonName .. "!")  -- debugging check line
		if buttonName == "LeftButton" then
			print("needs left click command")
		-- elseif buttonName == "MiddleButton" then
			-- command2
		elseif buttonName == "RightButton" then
			print("needs right click command")
		end
	end,
	funcOnEnter = function(button)
		MenuUtil.ShowTooltip(button, function(tooltip)
			tooltip:SetText("Raider.IO Mythic Plus, Raiding, and Recruitment")
		end)
	end,
	funcOnLeave = function(button)
		MenuUtil.HideTooltip(button)
	end,
})
```

**Comment by JPEscher** [comment]
hope that helps

**Comment by JPEscher** [comment]
tried to be more helpful. forked, and added what worked with my playing on the local add on.
https://github.com/RaiderIO/raiderio-addon/pull/291

hope this helps, is liked, and accepted. i completely understand if there's some need for tweaks to make it perfect.

**Comment by jahraphael** [comment]
Thanks for bringing this up. This got us chatting yesterday, and Vlad pushed a change with a fix for the issue (the bundled library was out of date). Let us know if you're still running into any problems with the addons compartment.
