### ISSUE TITLE
Frame drop when hovering gamemenu button

### ISSUE THREAD

**Issue by XiconQoo** [RaiderIO/raiderio-addon#58]
There is a reproducable behaviour of frames dropping when hovering the game menu button with no other addons enabled.

The effect is most recognizable when hovering over the "?" button very frequently.

**Comment by WFrancois** [comment]
Hey !

I believe this issue is related to #21 ?

**Comment by XiconQoo** [comment]
Hey WFrancois,

this does not happen on hovering players.

**Comment by WFrancois** [comment]
Well, as Vlad said : 
> The reason for it is simple; because the addon modules that contain the actual data for the players is so big, each time you mouse anything on the UI that shows performance information like CPU/RAM statistics, it will lag you as the game is checking the size of the loaded data, and it's around 50 MB per faction in EU and it will do a full re-check each time you mouse over those UI elements.

So it's each time you mouse over performance information ?

**Comment by XiconQoo** [comment]
Guess I was too quick on reading... yes you are right, its beacuse of the CPU/RAM statistics. What event is triggering there but not when hovering a player to eventually cause lag?

**Comment by WFrancois** [comment]
I guess it's when the game check the total size of the loaded data (as Vlad said :p), something we don't do when we only fetch one character.
