### ISSUE TITLE
lua error - Sep 5th release

### ISSUE THREAD

**Issue by JensBlomsterwall** [RaiderIO/raiderio-addon#65]
Date: 2018-09-05 19:03:17
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\RaiderIO\core.lua line 2113:
   attempt to index field 'dungeons' (a nil value)
Debug:
   RaiderIO\core.lua:2113:
      RaiderIO\core.lua:2065
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1376: ContainerFrameItemButton_OnEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:
tooltip = GameTooltip {
 0 = <userdata>
 numMoneyFrames = 2
 shoppingTooltips = <table> {
 }
 BottomOverlay = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 template = "Transparent"
 updateTooltip = 0.16599999815226
 comparing = false
 ignoreUpdates = true
 SetUnitAura = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 needsReset = true
 SetUnitBuff = <function> defined =[C]:-1
 TMW_SetSpellByIDWithClassIcon = <function> defined @Interface\AddOns\TellMeWhen\Components\Core\Spells\ClassSpellCache.lua:214
 SetUnitDebuff = <function> defined =[C]:-1
 hasMoney = 1
}
_ = "Mythic Keystone"
link = "[Keystone: Freehold (2)]"
patterns = <table> {
 1 = "keystone:%d+:(%d+):(%d+):(%d+):(%d+):(%d+)"
 2 = "item:138019:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:(%d+):(%d+):(%d+):(%d+):(%d+)"
 3 = "item:158923:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:.-:(%d+):(%d+):(%d+):(%d+):(%d+)"
}
inst = 245
lvl = 2
a1 = "10"
a2 = "0"
a3 = "0"
baseScore = 20
index = 2
n = 0
(for index) = 0
(for limit) = 0
(for step) = 1
i = 0
unit = "player"
profile = <table> {
 profile = <table> {
 }
 length = 0
 outputFlag = 8
 dataType = 1
}
(*temporary) = nil
(*temporary) = "player"
(*temporary) = 8
(*temporary) = "player"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string"
(*temporary) = "nil"
(*temporary) = "nil"
(*temporary) = 2
(*temporary) = "attempt to index field 'dungeons' (a nil value)"
ns = <table> {
 HasPlayerProfile = <function> defined @Interface\AddOns\RaiderIO\core.lua:1093
 realmSlugs = <table> {
 }
 ShowTooltip = <function> defined @Interface\AddOns\RaiderIO\core.lua:1155
 TooltipProfileOutput = <table> {
 }
 GetDungeonWithData = <function> defined @Interface\AddOns\RaiderIO\core.lua:255
 IS_DB_OUTDATED = <table> {
 }
 EXPORT_JSON = RaiderIO_ExportButton {
 }
 CONFIG = <table> {
 }
 DEBUG_MODE = false
 LFD_ACTIVITYID_TO_DUNGEONID = <table> {
 }
 dungeons = <table> {
 }
 GetNameAndRealm = <function> defined @Interface\AddOns\RaiderIO\core.lua:397
 PROFILE_UI = RaiderIO_ProfileTooltip {
 }
 enableTooltipCaching = true
 regionIDs = <table> {
 }
 PLAYER_REGION = "eu"
 L = <table> {
 }
 dataProvider = <table> {
 }
 PLAYER_FACTION = 2
 OUTDATED_DAYS = <table> {
 }
 GetPlayerProfile = <function> defined @Interface\AddOns\RaiderIO\core.lua:1002
 CONST_DUNGEONS = <table> {
 }
 scoreTiers = <table> {
 }
 addon = <unnamed> {
 }
 GUILD_BEST_FRAME = RaiderIO_GuildBestFrame {
 }
 GetStarsForUpgrades = <function> defined @Interface\AddOns\RaiderIO\core.lua:459
 OUTDATED_HOURS = <table> {
 }
 SEARCH_INIT = <function> defined @Interface\AddOns\RaiderIO\search.lua:178
 IsSameLocale = <function> defined @Interface\AddOns\RaiderIO\locale/locale.lua:15
 ProfileOutput = <table> {
 }
 scoreLevelStats = <table> {
 }
 addonConfig = <table> {
 }
 CompareDungeon = <function> defined @Interface\AddOns\RaiderIO\core.lua:264
 NewLocale = <function> defined @Interface\AddOns\RaiderIO\locale/locale.lua:11
 scoreTiersSimple = <table> {
 }
}
KEYSTONE_LEVEL_TO_BASE_SCORE = <table> {
 15 = 161
 2 = 20
 4 = 40
 8 = 80
 16 = 177
 17 = 195
 9 = 90
 18 = 214
 5 = 50
 10 = 100
 20 = 259
 21 = 285
 11 = 110
 22 = 314
 3 = 30
 6 = 60
 12 = 121
 24 = 380
 30 = 673
 25 = 418
 13 = 133
 26 = 459
 23 = 345
 7 = 70
 14 = 146
 28 = 556
 27 = 505
 29 = 612
 19 = 236
}
L = <table> {
 SHOW_MAINS_SCORE_DESC = "Shows the player's Main's score for the current season. Players must have registered on Raider.IO and declared a character as their main."
 SHOW_MAINS_SCORE = "Show Main's Season Score"
 INVERSE_PROFILE_MODIFIER = "Invert My M+ Profile Tooltip Modifier"
 UNKNOWN_SERVER_FOUND = "%s has encountered a new server. Please write down this information { %s , %s } and report it to the developers. Thank you!"
 DUNGEON_SHORT_NAME_AD = "AD"
 INVERSE_PROFILE_MODIFIER_DESC = "Enabling this will invert the behavior of the My M+ Profile Tooltip modifier (shift/ctrl/alt): hold to toggle the view between Personal/Leader profile or Leader/Person
AddOns:

**Comment by WFrancois** [comment]
Hey !

This should be fix in the latest release !

Thanks for the report :)
