### ISSUE TITLE
Lua Error  - The latest version

### ISSUE THREAD

**Issue by BlueNightSky** [RaiderIO/raiderio-addon#68]
Multiple errors will occur when you log in to the game.
Here is the first error:
`1x RaiderIO\locale/enUS.lua:3: attempt to call method 'NewLocale' (a nil value)
RaiderIO\locale/enUS.lua:3: in main chunk

Locals:
_ = "RaiderIO"
ns = <table> {
 realmSlugs = <table> {
 }
 regionIDs = <table> {
 }
 scoreLevelStats = <table> {
 }
 scoreTiersSimple = <table> {
 }
 scoreTiers = <table> {
 }
 dungeons = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 realmSlugs = <table> {
 }
 regionIDs = <table> {
 }
 scoreLevelStats = <table> {
 }
 scoreTiersSimple = <table> {
 }
 scoreTiers = <table> {
 }
 dungeons = <table> {
 }
}
(*temporary) = "attempt to call method 'NewLocale' (a nil value)"`

**The second error:**
`1x RaiderIO\core.lua:110: attempt to index local 'L' (a nil value)
RaiderIO\core.lua:110: in main chunk

Locals:
addonName = "RaiderIO"
ns = <table> {
 scoreTiers = <table> {
 }
 DEBUG_MODE = true
 dungeons = <table> {
 }
 realmSlugs = <table> {
 }
 regionIDs = <table> {
 }
 addonConfig = <table> {
 }
 CONFIG = <table> {
 }
 scoreLevelStats = <table> {
 }
 scoreTiersSimple = <table> {
 }
}
unpack = <function> defined =[C]:-1
sort = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
floor = <function> defined =[C]:-1
min = <function> defined =[C]:-1
max = <function> defined =[C]:-1
lshift = <function> defined =[C]:-1
rshift = <function> defined =[C]:-1
band = <function> defined =[C]:-1
bor = <function> defined =[C]:-1
bxor = <function> defined =[C]:-1
PAYLOAD_BITS = 13
PAYLOAD_MASK = 8191
LOOKUP_MAX_SIZE = 262143
uiHooks = <table> {
}
profileCache = <table> {
}
profileCacheTooltip = <table> {
}
dataProviderQueue = <table> {
}
dataProvider = nil
PLAYER_FACTION = nil
PLAYER_REGION = nil
IS_DB_OUTDATED = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
OUTDATED_DAYS = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
OUTDATED_HOURS = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
INVALID_DATA_MESSAGE_SENT = false
CONST_REALM_SLUGS = <table> {
 Al'Akir = "alakir"
 巨龙之吼 = "dragonmaw"
 MarécagedeZangar = "marecage-de-zangar"
 Akama = "akama"
 AbyssalMaw = "abyssal-maw"
 LichKing = "lich-king"
 Tyrande = "tyrande"
 玛诺洛斯 = "mannoroth"
 Frostwolf = "frostwolf"
 Echsenkessel = "echsenkessel"
 ScarshieldLegion = "scarshield-legion"
 KultderVerdammten = "kult-der-verdammten"
 Feathermoon = "feathermoon"
 Ysondre = "ysondre"
 헬스크림 = "hellscream"
 血吼 = "gorehowl"
 Gilneas = "gilneas"
 刺骨利刃 = "daggerspine"
 줄진 = "zuljin"
 Agamaggan = "agamaggan"
 DieAldor = "die-aldor"
 Gundrak = "gundrak"
 윈드러너 = "windrunner"
 莱索恩 = "lethon"
 알렉스트라자 = "alexstrasza"
 Azgalor = "azgalor"
 아즈샤라 = "azshara"
 DieSilberneHand = "die-silberne-hand"
 通灵学院 = "scholomance"
 Loken = "loken"
 불타는군단 = "burning-legion"
 Ambossar = "ambossar"
 艾苏恩 = "aszune"
 렉사르 = "rexxar"
 DreadmistPeak = "dreadmist-peak"
 듀로탄 = "durotan"
 海加尔 = "hyjal"
 Голдринн = "goldrinn"
 Al'ar = "alar"
 ShrineoftheDormantFlame = "shrine-of-the-dormant-flame"
 嚎风峡湾 = "howling-fjord"
 Trollbane = "trollbane"
 斩魔者 = "demonslayer"
 范克里夫 = "vancleef"
 가로나 = "garona"
 龙骨平原 = "dragonblight"
 Daggerspine = "daggerspine"
 远古海滩 = "strand-of-the-ancients"
 Angerboda = "angerboda"
 银月 = "silvermoon"
 黑龙军团 = "black-dragonflight"
 Winterspring = "winterspring"
 普瑞斯托 = "prestor"
 黑锋哨站 = "ebon-watch"
 阿纳克洛斯 = "anachronos"
 ПиратскаяБухта = "booty-bay"
 风行者 = "windrunner"
 StonetalonPeak = "stonetalon-peak"
 耐普图隆 = "neptulon"
 Forscherliga = "forscherliga"
 Arathor = "arathor"
 神圣之歌 = "holy-chanter"
 Gruul = "gruul"
 希雷诺斯 = "searinox"
 末日行者 = "doomwalker"
 黑暗魅影 = "dark-phantom"
 黑暗虚空 = "twisting-nether"
 艾维娜 = "aviana"
 无尽之海 = "the-great-sea"
 Dreadmaul = "dreadmaul"
 黑暗之矛 = "darkspear"
 黑手军团 = "blackhand"
 Pozzodell'Eternità = "pozzo-delleternita"
 DasSyndikat = "das-syndikat"
 黄金之路 = "gold-road"
 Kor'gall = "korgall"
 麦迪文 = "medivh"
 奎尔丹纳斯 = "quedanas"
 Talnivarr = "talnivarr"
 Windrunner = "windrunner"
 麦维影歌 = "maiev-shadowsong"
 麦姆 = "maim"
 鹰巢山 = "aerie-peak"
 德拉诺 = "draenor"
 阿扎达斯 = "archaedas"
 TheSha'tar = "the-shatar"
 纳克萨玛斯 = "naxxramas"
 巨龍之喉 = "dragonmaw"
 Felmyst = "felmyst"
 Gul'dan = "guldan"
 鬼雾峰 = "dreadmist-peak"
 瑟莱德丝 = "theradras"
 Sunwell = "sunwell"
 ChamberofAspects = "chamber-of-aspects"
 Vaelastrasz = "vaelastrasz"
 苏拉玛 = "suramar"
 Frostwhisper = "frostwhisper"
 Rashgarroth = "rashgarroth"
 Khaz'goroth = "khazgoroth"
 말퓨리온 = "malfurion"
 Jin'do = "jindo"
 藏宝海湾 = "booty-bay"
 ShatteredHalls = "shattered-halls"
 库尔提拉斯 = "kul-tiras"
 Skettis = "skettis"
 迅捷微风 = "`

**The third error:**
`1x RaiderIO\guildbest.lua:96: attempt to index upvalue 'L' (a nil value)
RaiderIO\guildbest.lua:96: in function <RaiderIO\guildbest.lua:94>

Locals:
self = <unnamed> {
 0 = <userdata>
 text = RaiderIO_GuildBestFrameText {
 }
 OnShow = <function> defined @RaiderIO\guildbest.lua:102
 OnLoad = <function> defined @RaiderIO\guildbest.lua:94
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = RaiderIO_GuildBestFrameText {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'L' (a nil value)"
L = nil`

**The fourth error:**
`1x RaiderIO\exportjson.lua:31: attempt to index local 'L' (a nil value)
RaiderIO\exportjson.lua:31: in main chunk

Locals:
addonName = "RaiderIO"
ns = <table> {
 scoreTiers = <table> {
 }
 DEBUG_MODE = true
 GUILD_BEST_FRAME = RaiderIO_GuildBestFrame {
 }
 dungeons = <table> {
 }
 PROFILE_UI = RaiderIO_ProfileTooltip {
 }
 realmSlugs = <table> {
 }
 SEARCH_INIT = <function> defined @RaiderIO\search.lua:182
 regionIDs = <table> {
 }
 addonConfig = <table> {
 }
 CONFIG = <table> {
 }
 scoreLevelStats = <table> {
 }
 scoreTiersSimple = <table> {
 }
}
band = <function> defined =[C]:-1
bor = <function> defined =[C]:-1
L = nil
ExportButton = RaiderIO_ExportButton {
 0 = <userdata>
 Icon = <unnamed> {
 }
 Border = <unnamed> {
 }
}
StaticPopupName = "RAIDERIO_EXPORTJSON_DIALOG"
(*temporary) = <table> {
 CLIQUE_CONFIRM_PROFILE_DELETE = <table> {
 }
 CONFIRM_REMOVE_FRIEND = <table> {
 }
 BIS_CONFIRM_DELETE_HISTORY = <table> {
 }
 BugSackSendBugs = <table> {
 }
 CONFIRM_REDOCK_CHAT = <table> {
 }
 BETTER_ADDONLIST_ERROR_NAME = <table> {
 }
 REMOVE_GUILDMEMBER = <table> {
 }
 QUEST_ACCEPT_LOG_FULL = <table> {
 }
 DELETE_QUEST_ITEM = <table> {
 }
 TRADE_POTENTIAL_BIND_ENCHANT = <table> {
 }
 SET_GUILDPLAYERNOTE = <table> {
 }
 ABANDON_PET = <table> {
 }
 USE_NO_REFUND_CONFIRM = <table> {
 }
 CONFIRM_GORGROND_GARRISON_CHOICE = <table> {
 }
 DELETE_ITEM = <table> {
 }
 ADD_RAIDMEMBER = <table> {
 }
 CONFIRM_BLOCK_INVITES = <table> {
 }
 CAERDON_WARDROBE_MULTIPLE_BAG_ADDONS = <table> {
 }
 TRANSMOG_OUTFIT_SOME_INVALID_APPEARANCES = <table> {
 }
 CONFIRM_OVERWRITE_TRANSMOG_OUTFIT = <table> {
 }
 SAVED_VARIABLES_TOO_LARGE = <table> {
 }
 RESURRECT_NO_TIMER = <table> {
 }
 SET_BNFRIENDNOTE = <table> {
 }
 UNLEARN_SPECIALIZATION = <table> {
 }
 CONFIRM_HIGH_COST_ITEM = <table> {
 }
 BESTINSLOT_CONFIRMCHARIMPORT = <table> {
 }
 CHAT_CHANNEL_PASSWORD = <table> {
 }
 GUILDBANK_WITHDRAW = <table> {
 }
 UNLEARN_SKILL = <table> {
 }
 CONFIRM_LOOT_ROLL = <table> {
 }
 HELP_TICKET_QUEUE_DISABLED = <table> {
 }
 EXTVENDOR_CONFIRM_RESET_BLACKLIST = <table> {
 }
 GARRISON_BOOT = <table> {
 }
 CONFIRM_AZERITE_EMPOWERED_RESPEC = <table> {
 }
 TAKE_GM_SURVEY = <table> {
 }
 POSTAL_NEW_PROFILE = <table> {
 }
 CONFIRM_COMBAT_FILTER_DEFAULTS = <table> {
 }
 GM_RESPONSE_RESOLVE_CONFIRM = <table> {
 }
 ERR_SOR_STARTING_EXPERIENCE_INCOMPLETE = <table> {
 }
 TALENTS_INVOLUNTARILY_RESET = <table> {
 }
 GM_RESPONSE_MUST_RESOLVE_RESPONSE = <table> {
 }
 CONFIRM_REPORT_BATTLEPET_NAME = <table> {
 }
 IGR_BILLING_NAG = <table> {
 }
 PLR_ROLL_CANCEL = <table> {
 }
 SET_BN_BROADCAST = <table> {
 }
 ERROR_CINEMATIC = <table> {
 }
 CONFIRM_COMBAT_FILTER_DELETE = <table> {
 }
 CONFIRM_REPORT_PET_NAME = <table> {
 }
 CONFIRM_BUY_GUILDBANK_TAB = <table> {
 }
 LOOT_BIND = <table> {
 }
 DUEL_REQUESTED = <table> {
 }
 BFMGR_PLAYER_LOW_LEVEL = <table> {
 }
 SKINNED = <table> {
 }
 ADD_IGNORE = <table> {
 }
 CONFIRM_UPGRADE_ITEM = <table> {
 }
 CONFIRM_AZERITE_EMPOWERED_BIND = <table> {
 }
 TRADE_POTENTIAL_REMOVE_TRANSMOG = <table> {
 }
 ATR_MEMORIZE_TEXT_BLANK = <table> {
 }
 CONFIRM_DELETE_EQUIPMENT_SET = <table> {
 }
 DELETE_MONEY = <table> {
 }
 DELETE_GOOD_ITEM = <table> {
 }
 PLR_MASTERLOOT_ASK = <table> {
 }
 GOSSIP_CONFIRM = <table> {
 }
 BATTLENET_UNAVAILABLE = <table> {
 }
 USE_GUILDBANK_REPAIR = <table> {
 }
 BAZOOKA_DISABLE_PLUGIN = <table> {
 }
 TRANSMOG_OUTFIT_CHECKING_APPEARANCES = <table> {
 }
 BILLING_NAG = <table> {
 }
 EXPERIMENTAL_CVAR_WARNING = <table> {
 }
 WEB_PROXY_FAILED = <table> {
 }
 CONFIRM_BINDER = <table> {
 }
 BESTINSLOT_CONFIRMDELETECUSTOMITEM = <table> {
 }
 CONFIRM_SUMMON_STARTING_AREA = <table> {
 }
 TOO_MANY_LUA_ERRORS = <table> {
 }
 TRADE_REPLACE_ENCHANT = <table> {
 }
 ATR_SL_REQUEST_SHARING = <table> {
 }
 VOID_DEPOSIT_CONFIRM = <table> {
 }
 CONFIRM_REFUND_MAX_ARENA_POINTS = <table> {
 }
 RENAME_PET = <table> {
 }
 CONFIRM_GUILD_PROMOTE = <table> {
 }
 SET_GUILD_COMMUNITIY_NOTE = <table> {
 }
 LFG_LIST_ENTRY_EXPIRED_TOO_MANY_PLAYERS = <table> {
 }
 CONFIRM_AZERITE_EMPOWERED_SELECT_POWER = <table> {
 }
 CONFIRM_GUILD_LEAVE = <table> {
 }
 LEVEL_GRANT_PROPOSED_ALLIED_RACE = <table> {
 }
 BN_BLOCK_FAILED_TOO_MANY_CID = <table> {
 }
 CONFIRM_RE`

**In fact, there are a total of 9 errors, but I think some errors are affected by other errors, so I don’t have all the reports.**

**Comment by Vladinator89** [comment]
This is very strange.

I did notice that you got the files from the git apparently, so just to make it certain you do not experience issues by installing it the regular way, could you do this for me and get the addon from curseforge? https://www.curseforge.com/wow/addons/raiderio

You can also install it by using the Twitch Client ( https://app.twitch.tv/download ) or the RaiderIO Client ( https://raider.io/addon )

**Comment by BlueNightSky** [comment]
I have downloaded the latest version from Curse as you said, the previous error is gone.
But there is still a new error, but at least it works fine.
Maybe it's a problem with the Exlist addon?
`1x RaiderIO\core.lua:2261: invalid option in `format'
RaiderIO\core.lua:2261: in function <RaiderIO\core.lua:2256>
RaiderIO\core.lua:2267: in function `GetScore'
Exlist\Modules\RaiderIOScores.lua:33: in function <Exlist\Modules\RaiderIOScores.lua:25>
[C]: in function `xpcall'
Exlist\Exlist-1.2.10.lua:2295: in function `OnEvent'
Exlist\Exlist-1.2.10.lua:2318: in function `SendFakeEvent'
Exlist\Exlist-1.2.10.lua:2221: in function <Exlist\Exlist.lua:2219>
Exlist\Exlist-1.2.10.lua:2274: in function `OnEvent'
Exlist\Exlist-1.2.10.lua:2318: in function `SendFakeEvent'
Exlist\Exlist-1.2.10.lua:2280: in function <Exlist\Exlist.lua:2280>`

**Comment by Vladinator89** [comment]
Thanks. This helps get a bit closer to the root of the issue you're experiencing.

It does seem like Exlist is using code in RaiderIO but ends up erroring, it's still a valuable error report for us to look at. I hope the author of Exlist is around and can look at their code to update with the new API we added for BfA.

**Comment by Vladinator89** [comment]
I downloaded Exlist and the current version doesn't throw that error. If you update Exlist you should be good to go once more.

**Comment by BlueNightSky** [comment]
I downloaded Exlist(version:1.2.11), but still have this error:
`1x RaiderIO\core.lua:2261: invalid option in `format'
RaiderIO\core.lua:2261: in function <RaiderIO\core.lua:2256>
RaiderIO\core.lua:2267: in function `GetScore'
Exlist\Modules\RaiderIOScores.lua:33: in function <Exlist\Modules\RaiderIOScores.lua:25>
[C]: in function `xpcall'
Exlist\Exlist-1.2.11.lua:2286: in function `OnEvent'
Exlist\Exlist-1.2.11.lua:2309: in function `SendFakeEvent'
Exlist\Exlist-1.2.11.lua:2212: in function <Exlist\Exlist.lua:2210>
Exlist\Exlist-1.2.11.lua:2265: in function `OnEvent'
Exlist\Exlist-1.2.11.lua:2309: in function `SendFakeEvent'
Exlist\Exlist-1.2.11.lua:2271: in function <Exlist\Exlist.lua:2271>`

**Comment by Vladinator89** [comment]
It's very odd because when I install Exlist from https://www.curseforge.com/wow/addons/exlist and load it all I see is the expected chat notification https://i.imgur.com/SSYxqhQ.png but no error.

I did push a small update to RaiderIO yesterday that would fix a small issue to avoid getting errors when using an outdated addon using RaiderIO to get score for players, it should appear as yellow text once, not a lua error dialog like you're having.

My only tip is update both from curseforge again today, if you can also do delete the old folders inside your WoW\Interface\AddOns folder, then put the new addons in there and make sure you quit WoW first, then boot it up again after you're done freshly installing both addons and if it still doesn't work do let me know.

**Comment by BlueNightSky** [comment]
I downloaded Raider.IO Mythic Plus v201809160600, but there is still this error, I really don't know why?

I have deleted the old folder and installed the new one as you said. and quit Wow then reboot.

Well, At least the addon works fine, but this error is a bit annoying!

**Comment by WFrancois** [comment]
Hey, hopefully this issue is not here anymore, let us know if it's still there !
