### ISSUE TITLE
Rio score doesn't update

### ISSUE THREAD

**Issue by Hierophante** [RaiderIO/raiderio-addon#70]
![rio](https://user-images.githubusercontent.com/43506077/45922371-609cdf00-be98-11e8-94e1-10ba45668881.png)
Here is a picture of all my best keys IG
![rio 2](https://user-images.githubusercontent.com/43506077/45922387-cab58400-be98-11e8-88ed-2d1aa3d20478.png)
And this is a picture of my keys online
I cant find a way to get them to appear on my rio score. I did at least 2 Motherlode keys but none of them are counted. 
Is there any way to fix this ?

**Comment by Vladinator89** [comment]
It takes up to a day for the new addon to build and deploy on https://wow.curseforge.com/projects/raiderio If you use Twitch you can get the updates that way, or the RaiderIO Client https://raider.io/addon as it would make updating the scores easier and more automated.

As long the runs show on the website they will be included in the addon in the next update. So it's good you checked your website profile for the runs to see they are on there.
