### ISSUE TITLE
Implement option to filter out LFG results from capped servers

### ISSUE THREAD

**Issue by Petoovee** [RaiderIO/raiderio-addon#79]
This could be done by storing the current "Lowest Leaderboard Keystones", assuming that any keystone that is full is impossible to enter. Realm can be extracted from C_LFGList.GetSearchResultInfo() using substrings.

An extended implementation of this could also include the same functionality but for LFGListApplicationViewer, where leaders can see if the applicant´s realm has open leaderboard spots open for the current dungeon.

**Comment by 0xbs** [comment]
Providing information if the leader boards are already full in the player's tooltip would indeed be a great addition to the addon. At the end of the week, it is almost impossible to get ranked on some realms.

**Comment by WFrancois** [comment]
Hey !

With the new feature from blizzard, this shouldn't be that much of an issue (the new feature from blizzard allows to grab the run directly from your character instead of from a "leaderboard").
