### ISSUE TITLE
Raid score not updating

### ISSUE THREAD

**Issue by equiiaddict** [RaiderIO/raiderio-addon#82]
Hi,

I have completed 7/8 N and 4/8 H raids on my main character, but my Raider IO score still hasn't changed from 5/8 N. I'm not sure why this is or if I need to do something else? I waited a week because I figured it might update once my weekly raid lockout expired but it hasn't yet.

Thank you

**Comment by WFrancois** [comment]
Hey, sorry for the delay, do you still have this issue ?
