### ISSUE TITLE
Copy raider.io URL in LookingForGroup-Addon not working (Lua Error)

### ISSUE THREAD

**Issue by MisterT87** [RaiderIO/raiderio-addon#83]
Heyho, first of all: Thanks for your great work and this addon ;)

I am using LookingForGroup(LFG) Addon from curseforge and with Raider.io Plugin...
If I try to copy Raider.io URL on "Requests" window in LFG-Addon nothing happens...

I enabled scripterrors (with ./console scripterrors 1) and reload my UI
Now If I try to copy Raider.io URL on Requests window - I Will get the following Error:

> Message: Interface\AddOns\RaiderIO\core.lua:1834: bad argument #3 to 'format' (string expected, got nil)
> Time: Wed Nov 14 10:20:16 2018
> Count: 1
> Stack: Interface\AddOns\RaiderIO\core.lua:1834: bad argument #3 to 'format' (string expected, got nil)
> [C]: in function `format'
> Interface\AddOns\RaiderIO\core.lua:1834: in function <Interface\AddOns\RaiderIO\core.lua:1831>
> Interface\AddOns\RaiderIO\core.lua:2210: in function <Interface\AddOns\RaiderIO\core.lua:2209>
> Interface\AddOns\RaiderIO\core.lua:2269: in function <Interface\AddOns\RaiderIO\core.lua:2268>
> 
> Locals: (*temporary) = "https://raider.io/characters/%s/%s/%s"
> (*temporary) = "eu"
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "string expected, got nil"

**Comment by MisterT87** [comment]
Update: Bug still exist with newest Raider.io Update (v201811160600)

**Comment by WFrancois** [comment]
Hey ! Sorry for the delay on the answer, do you still have this issue ?
