### ISSUE TITLE
Здравствуйте. Проблема: сменил имя персонажа и больше не показывает ни прогресс,ни очки R.io и даже при проходе рейда и подземелий с новым именем.

### ISSUE THREAD

**Issue by tolyan99** [RaiderIO/raiderio-addon#88]

**Comment by tolyan99** [comment]
как вернуть очки rio со старого имени?

**Comment by tolyan99** [comment]
https://raider.io/characters/eu/gordunni/%D0%92%D0%B4%D0%B2%D1%81%D0%BF%D0%B5%D1%86%D0%BD%D0%B0%D0%B7

**Comment by tolyan99** [comment]
новый ник этого персонажа  Маркуська

**Comment by WFrancois** [comment]
Hey ! (We don't really speak russian :D)

If it's for a transfer and merging score, you can come on [Raiderio's discord server](https://discord.gg/raider) and post your before and after link in the #bug-reports channel.

(Note though that's it's the holiday, so might be a bit slower)
