### ISSUE TITLE
Addon will not update

### ISSUE THREAD

**Issue by David-Camara** [RaiderIO/raiderio-addon#89]
I've tried reinstalling the addon and it is still saying that the scores are x days old. The information will not update. Please help!

![image](https://user-images.githubusercontent.com/46068519/50374337-84b4ad00-05ba-11e9-8473-99ec6b9cc868.png)

**Comment by WFrancois** [comment]
Hey,

If you're using the raiderio client, check that the directory is the new `_retail_` folder (added in the new patch).

If you still have this issue, come ask in discord, it'll be easier to narrow down the issue :) 

[Discord](https://discord.gg/raider)
