### ISSUE TITLE
Mythic+ scores not updating now over 2 wks behind

### ISSUE THREAD

**Issue by Maricit** [RaiderIO/raiderio-addon#90]

**Comment by WFrancois** [comment]
Hey!

Are you using the raiderio client? If so, is the directory for world of Warcraft pointing to the `_retail_` folder? (this changed with the new patch)

**Comment by Maricit** [comment]
do not have the best knowledge of this. I did notice I have the same files in interface/addons  and another set in _retail_/interface/addons  is that the problem

**Comment by WFrancois** [comment]
Are you using the raiderio application or twitch?

**Comment by Maricit** [comment]
Twitch

**Comment by WFrancois** [comment]
Then when you look at twitch configuration, what's the location for world of Warcraft? It should be the `_retail_` folder

**Comment by Maricit** [comment]
Sry for this. I am in twitch not sure how to where to look for configuration

**Comment by Maricit** [comment]
Ty for the help I did find it. Was pointing at beta. Not sure why it changed

**Comment by WFrancois** [comment]
So in twitch, you go under settings, then `Addons`, then `Game Specific`, and you should be able to find your `Install Location` there :)

**Comment by Maricit** [comment]
yes
