### ISSUE TITLE
Addon problem

### ISSUE THREAD

**Issue by alfalasi77** [RaiderIO/raiderio-addon#94]
Hello

I finished 9/9N BoD and 2/9HC BoD, and its updated on the website and the clint, but not my ingame addon.

How can I fix this problem or can yo u fix it for me?

Thanks.

**Comment by roots84** [comment]
Hello,

did you download and run the Raider.io desktop client? (https://raider.io/addon)
This tool will download the latest data from the Raider.io website and make it available for you ingame.

**Comment by jahraphael** [comment]
Not a bug. Issue is related to the way the addon data refreshes: https://raiderio.reamaze.com/kb/raider-dot-io-mythic-plus-addon/when-is-the-raiderio-addon-updated
