### ISSUE TITLE
It's not showing me my own stats

### ISSUE THREAD

**Issue by MrsTonieB** [RaiderIO/raiderio-addon#95]
why is it that I can see others but never my own ? Desktop DL'ed etc -- hubby has same addons I do and not having this issue--- Already uninstalled and reinstalled etc

**Comment by WFrancois** [comment]
Hey !

That depends on a lot of condition.

Mainly : 
- Your character needs to have more than 200 score
- Your character needs to have been scanned less than 28 days ago
