### ISSUE TITLE
Desktop client: Validation failure: local files modified

### ISSUE THREAD

**Issue by royipressburger** [RaiderIO/raiderio-addon#96]
Hi..

I just installed the desktop client for the first time, after setting all up the client started downloading some files.
After a short time I got an error saying `Validation failure: local files modified`.

I tried install and reinstall, and did not work.

I tried changing the `ADDON DOWNLOAD CHANNEL` to `Testing` in settings, then it worked.
After it downloaded the addon from testing I changed it back to `Release` and it worked, but for some reason its not look like the right way.

Any ideas?

**Comment by WFrancois** [comment]
Hey !

There was indeed an issue that just got resolved :) 

Here's what @jahraphael said to fix it : 

> For those still experiencing problems with the client giving the error "local files modified": We just deployed another fix to the build. Try fully closing and exit the Raider.IO client and start it up again to get the latest changes. You should show as getting version v201902190600-cf if you are getting the fixed version.

**Comment by royipressburger** [comment]
Cool thanks for the fast response
