### ISSUE TITLE
Mixed seasons

### ISSUE THREAD

**Issue by T3ll1nG** [RaiderIO/raiderio-addon#97]
Hi,
the addon was great until season 2 hit. Now the addon shows a mix of season 1 & 2 which results in the addon being useless apart from the copy url function. Please make it possible to only show current season, because it really doesn't matter how many timed runs / high level keys or which roles a character did last season. Atm the addon sums this things up, which leads to roles that have only been played last season, timed runs that happend last season and keys that were played last season being shown in the tooltip.

**Comment by WFrancois** [comment]
Hey !

We're currently doing an alpha to change how the season are displayed :)

To try it out, you can use the RaiderIO client and set the release channel to "alpha".

Feel free to join RaiderIO discord if you want more info about it :) https://discord.gg/raider

Here's the main changes : 

![](https://cdn.discordapp.com/attachments/371022157683359744/547078697077833729/unknown.png)

**Comment by T3ll1nG** [comment]
Hi,
thanks for the fast response and yes the alpha fixes these problems. :-)
